spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/metabuild
    username: metabuild
    password: metabuild

logging:
  level:
    com.metabuild: DEBUG
    org.jooq: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
