/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedNoticesIndexRouteImport } from './routes/_authed/notices/index'
import { Route as AuthedSettingsWechatBindRouteImport } from './routes/_authed/settings/wechat-bind'
import { Route as AuthedNoticesIdRouteImport } from './routes/_authed/notices/$id'
import { Route as AuthedSystemUsersIndexRouteImport } from './routes/_authed/system/users/index'
import { Route as AuthedSystemRolesIndexRouteImport } from './routes/_authed/system/roles/index'
import { Route as AuthedSystemMenusIndexRouteImport } from './routes/_authed/system/menus/index'
import { Route as AuthedSystemDeptsIndexRouteImport } from './routes/_authed/system/depts/index'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNoticesIndexRoute = AuthedNoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsWechatBindRoute =
  AuthedSettingsWechatBindRouteImport.update({
    id: '/settings/wechat-bind',
    path: '/settings/wechat-bind',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedNoticesIdRoute = AuthedNoticesIdRouteImport.update({
  id: '/notices/$id',
  path: '/notices/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemUsersIndexRoute = AuthedSystemUsersIndexRouteImport.update({
  id: '/system/users/',
  path: '/system/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemRolesIndexRoute = AuthedSystemRolesIndexRouteImport.update({
  id: '/system/roles/',
  path: '/system/roles/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemMenusIndexRoute = AuthedSystemMenusIndexRouteImport.update({
  id: '/system/menus/',
  path: '/system/menus/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSystemDeptsIndexRoute = AuthedSystemDeptsIndexRouteImport.update({
  id: '/system/depts/',
  path: '/system/depts/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/notices/$id': typeof AuthedNoticesIdRoute
  '/settings/wechat-bind': typeof AuthedSettingsWechatBindRoute
  '/notices/': typeof AuthedNoticesIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/system/depts/': typeof AuthedSystemDeptsIndexRoute
  '/system/menus/': typeof AuthedSystemMenusIndexRoute
  '/system/roles/': typeof AuthedSystemRolesIndexRoute
  '/system/users/': typeof AuthedSystemUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/notices/$id': typeof AuthedNoticesIdRoute
  '/settings/wechat-bind': typeof AuthedSettingsWechatBindRoute
  '/notices': typeof AuthedNoticesIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/system/depts': typeof AuthedSystemDeptsIndexRoute
  '/system/menus': typeof AuthedSystemMenusIndexRoute
  '/system/roles': typeof AuthedSystemRolesIndexRoute
  '/system/users': typeof AuthedSystemUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authed/notices/$id': typeof AuthedNoticesIdRoute
  '/_authed/settings/wechat-bind': typeof AuthedSettingsWechatBindRoute
  '/_authed/notices/': typeof AuthedNoticesIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/system/depts/': typeof AuthedSystemDeptsIndexRoute
  '/_authed/system/menus/': typeof AuthedSystemMenusIndexRoute
  '/_authed/system/roles/': typeof AuthedSystemRolesIndexRoute
  '/_authed/system/users/': typeof AuthedSystemUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/notices/$id'
    | '/settings/wechat-bind'
    | '/notices/'
    | '/settings/'
    | '/system/depts/'
    | '/system/menus/'
    | '/system/roles/'
    | '/system/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/notices/$id'
    | '/settings/wechat-bind'
    | '/notices'
    | '/settings'
    | '/system/depts'
    | '/system/menus'
    | '/system/roles'
    | '/system/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/_authed/notices/$id'
    | '/_authed/settings/wechat-bind'
    | '/_authed/notices/'
    | '/_authed/settings/'
    | '/_authed/system/depts/'
    | '/_authed/system/menus/'
    | '/_authed/system/roles/'
    | '/_authed/system/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notices/': {
      id: '/_authed/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof AuthedNoticesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/wechat-bind': {
      id: '/_authed/settings/wechat-bind'
      path: '/settings/wechat-bind'
      fullPath: '/settings/wechat-bind'
      preLoaderRoute: typeof AuthedSettingsWechatBindRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notices/$id': {
      id: '/_authed/notices/$id'
      path: '/notices/$id'
      fullPath: '/notices/$id'
      preLoaderRoute: typeof AuthedNoticesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system/users/': {
      id: '/_authed/system/users/'
      path: '/system/users'
      fullPath: '/system/users/'
      preLoaderRoute: typeof AuthedSystemUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system/roles/': {
      id: '/_authed/system/roles/'
      path: '/system/roles'
      fullPath: '/system/roles/'
      preLoaderRoute: typeof AuthedSystemRolesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system/menus/': {
      id: '/_authed/system/menus/'
      path: '/system/menus'
      fullPath: '/system/menus/'
      preLoaderRoute: typeof AuthedSystemMenusIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/system/depts/': {
      id: '/_authed/system/depts/'
      path: '/system/depts'
      fullPath: '/system/depts/'
      preLoaderRoute: typeof AuthedSystemDeptsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedNoticesIdRoute: typeof AuthedNoticesIdRoute
  AuthedSettingsWechatBindRoute: typeof AuthedSettingsWechatBindRoute
  AuthedNoticesIndexRoute: typeof AuthedNoticesIndexRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSystemDeptsIndexRoute: typeof AuthedSystemDeptsIndexRoute
  AuthedSystemMenusIndexRoute: typeof AuthedSystemMenusIndexRoute
  AuthedSystemRolesIndexRoute: typeof AuthedSystemRolesIndexRoute
  AuthedSystemUsersIndexRoute: typeof AuthedSystemUsersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedNoticesIdRoute: AuthedNoticesIdRoute,
  AuthedSettingsWechatBindRoute: AuthedSettingsWechatBindRoute,
  AuthedNoticesIndexRoute: AuthedNoticesIndexRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSystemDeptsIndexRoute: AuthedSystemDeptsIndexRoute,
  AuthedSystemMenusIndexRoute: AuthedSystemMenusIndexRoute,
  AuthedSystemRolesIndexRoute: AuthedSystemRolesIndexRoute,
  AuthedSystemUsersIndexRoute: AuthedSystemUsersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
