/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.BizNoticeRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 通知公告
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNotice extends TableImpl<BizNoticeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.biz_notice</code>
     */
    public static final BizNotice BIZ_NOTICE = new BizNotice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizNoticeRecord> getRecordType() {
        return BizNoticeRecord.class;
    }

    /**
     * The column <code>public.biz_notice.id</code>. 主键（Snowflake）
     */
    public final TableField<BizNoticeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "主键（Snowflake）");

    /**
     * The column <code>public.biz_notice.tenant_id</code>. 租户 ID（v1 默认 0）
     */
    public final TableField<BizNoticeRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "租户 ID（v1 默认 0）");

    /**
     * The column <code>public.biz_notice.title</code>. 公告标题
     */
    public final TableField<BizNoticeRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(200).nullable(false), this, "公告标题");

    /**
     * The column <code>public.biz_notice.content</code>. 公告内容（富文本 HTML，后端 jsoup
     * 净化）
     */
    public final TableField<BizNoticeRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "公告内容（富文本 HTML，后端 jsoup 净化）");

    /**
     * The column <code>public.biz_notice.status</code>. 状态：0=草稿 1=已发布 2=已撤回
     */
    public final TableField<BizNoticeRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "状态：0=草稿 1=已发布 2=已撤回");

    /**
     * The column <code>public.biz_notice.pinned</code>. 是否置顶
     */
    public final TableField<BizNoticeRecord, Boolean> PINNED = createField(DSL.name("pinned"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "是否置顶");

    /**
     * The column <code>public.biz_notice.start_time</code>. 生效开始时间
     */
    public final TableField<BizNoticeRecord, OffsetDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "生效开始时间");

    /**
     * The column <code>public.biz_notice.end_time</code>. 生效结束时间
     */
    public final TableField<BizNoticeRecord, OffsetDateTime> END_TIME = createField(DSL.name("end_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "生效结束时间");

    /**
     * The column <code>public.biz_notice.owner_dept_id</code>. 所属部门 ID（数据权限）
     */
    public final TableField<BizNoticeRecord, Long> OWNER_DEPT_ID = createField(DSL.name("owner_dept_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "所属部门 ID（数据权限）");

    /**
     * The column <code>public.biz_notice.version</code>. 乐观锁版本号
     */
    public final TableField<BizNoticeRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "乐观锁版本号");

    /**
     * The column <code>public.biz_notice.created_by</code>. 创建人 ID
     */
    public final TableField<BizNoticeRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "创建人 ID");

    /**
     * The column <code>public.biz_notice.created_at</code>. 创建时间
     */
    public final TableField<BizNoticeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "创建时间");

    /**
     * The column <code>public.biz_notice.updated_by</code>. 最后修改人 ID
     */
    public final TableField<BizNoticeRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "最后修改人 ID");

    /**
     * The column <code>public.biz_notice.updated_at</code>. 最后修改时间
     */
    public final TableField<BizNoticeRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "最后修改时间");

    private BizNotice(Name alias, Table<BizNoticeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BizNotice(Name alias, Table<BizNoticeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("通知公告"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.biz_notice</code> table reference
     */
    public BizNotice(String alias) {
        this(DSL.name(alias), BIZ_NOTICE);
    }

    /**
     * Create an aliased <code>public.biz_notice</code> table reference
     */
    public BizNotice(Name alias) {
        this(alias, BIZ_NOTICE);
    }

    /**
     * Create a <code>public.biz_notice</code> table reference
     */
    public BizNotice() {
        this(DSL.name("biz_notice"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTICE_PINNED, Indexes.IDX_NOTICE_TENANT_CREATED, Indexes.IDX_NOTICE_TENANT_DEPT, Indexes.IDX_NOTICE_TENANT_STATUS);
    }

    @Override
    public UniqueKey<BizNoticeRecord> getPrimaryKey() {
        return Keys.BIZ_NOTICE_PKEY;
    }

    @Override
    public BizNotice as(String alias) {
        return new BizNotice(DSL.name(alias), this);
    }

    @Override
    public BizNotice as(Name alias) {
        return new BizNotice(alias, this);
    }

    @Override
    public BizNotice as(Table<?> alias) {
        return new BizNotice(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNotice rename(String name) {
        return new BizNotice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNotice rename(Name name) {
        return new BizNotice(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNotice rename(Table<?> name) {
        return new BizNotice(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNotice where(Condition condition) {
        return new BizNotice(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNotice where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNotice where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNotice where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNotice where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNotice where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNotice where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNotice where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNotice whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNotice whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
