/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.BizNoticeRecipientRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 通知接收人（发布时从 target 展开到具体用户）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNoticeRecipient extends TableImpl<BizNoticeRecipientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.biz_notice_recipient</code>
     */
    public static final BizNoticeRecipient BIZ_NOTICE_RECIPIENT = new BizNoticeRecipient();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizNoticeRecipientRecord> getRecordType() {
        return BizNoticeRecipientRecord.class;
    }

    /**
     * The column <code>public.biz_notice_recipient.id</code>.
     */
    public final TableField<BizNoticeRecipientRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.biz_notice_recipient.notice_id</code>.
     */
    public final TableField<BizNoticeRecipientRecord, Long> NOTICE_ID = createField(DSL.name("notice_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.biz_notice_recipient.user_id</code>.
     */
    public final TableField<BizNoticeRecipientRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.biz_notice_recipient.read_at</code>.
     * 已读时间（NULL=未读）
     */
    public final TableField<BizNoticeRecipientRecord, OffsetDateTime> READ_AT = createField(DSL.name("read_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "已读时间（NULL=未读）");

    /**
     * The column <code>public.biz_notice_recipient.created_at</code>.
     */
    public final TableField<BizNoticeRecipientRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private BizNoticeRecipient(Name alias, Table<BizNoticeRecipientRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BizNoticeRecipient(Name alias, Table<BizNoticeRecipientRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("通知接收人（发布时从 target 展开到具体用户）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.biz_notice_recipient</code> table
     * reference
     */
    public BizNoticeRecipient(String alias) {
        this(DSL.name(alias), BIZ_NOTICE_RECIPIENT);
    }

    /**
     * Create an aliased <code>public.biz_notice_recipient</code> table
     * reference
     */
    public BizNoticeRecipient(Name alias) {
        this(alias, BIZ_NOTICE_RECIPIENT);
    }

    /**
     * Create a <code>public.biz_notice_recipient</code> table reference
     */
    public BizNoticeRecipient() {
        this(DSL.name("biz_notice_recipient"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTICE_RECIPIENT_NOTICE, Indexes.IDX_NOTICE_RECIPIENT_USER, Indexes.UK_NOTICE_RECIPIENT);
    }

    @Override
    public UniqueKey<BizNoticeRecipientRecord> getPrimaryKey() {
        return Keys.BIZ_NOTICE_RECIPIENT_PKEY;
    }

    @Override
    public BizNoticeRecipient as(String alias) {
        return new BizNoticeRecipient(DSL.name(alias), this);
    }

    @Override
    public BizNoticeRecipient as(Name alias) {
        return new BizNoticeRecipient(alias, this);
    }

    @Override
    public BizNoticeRecipient as(Table<?> alias) {
        return new BizNoticeRecipient(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNoticeRecipient rename(String name) {
        return new BizNoticeRecipient(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNoticeRecipient rename(Name name) {
        return new BizNoticeRecipient(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNoticeRecipient rename(Table<?> name) {
        return new BizNoticeRecipient(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeRecipient where(Condition condition) {
        return new BizNoticeRecipient(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeRecipient where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeRecipient where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeRecipient where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeRecipient where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeRecipient where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeRecipient where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeRecipient where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeRecipient whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeRecipient whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
