/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.BizNoticeTargetRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 通知目标（多态关联：全员/部门/角色/用户）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNoticeTarget extends TableImpl<BizNoticeTargetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.biz_notice_target</code>
     */
    public static final BizNoticeTarget BIZ_NOTICE_TARGET = new BizNoticeTarget();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BizNoticeTargetRecord> getRecordType() {
        return BizNoticeTargetRecord.class;
    }

    /**
     * The column <code>public.biz_notice_target.id</code>.
     */
    public final TableField<BizNoticeTargetRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.biz_notice_target.notice_id</code>.
     */
    public final TableField<BizNoticeTargetRecord, Long> NOTICE_ID = createField(DSL.name("notice_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.biz_notice_target.target_type</code>. 目标类型：ALL=全员
     * DEPT=部门 ROLE=角色 USER=指定用户
     */
    public final TableField<BizNoticeTargetRecord, String> TARGET_TYPE = createField(DSL.name("target_type"), SQLDataType.VARCHAR(20).nullable(false), this, "目标类型：ALL=全员 DEPT=部门 ROLE=角色 USER=指定用户");

    /**
     * The column <code>public.biz_notice_target.target_id</code>. 目标 ID（ALL 时为
     * NULL，DEPT=部门ID，ROLE=角色ID，USER=用户ID）
     */
    public final TableField<BizNoticeTargetRecord, Long> TARGET_ID = createField(DSL.name("target_id"), SQLDataType.BIGINT, this, "目标 ID（ALL 时为 NULL，DEPT=部门ID，ROLE=角色ID，USER=用户ID）");

    /**
     * The column <code>public.biz_notice_target.created_at</code>.
     */
    public final TableField<BizNoticeTargetRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private BizNoticeTarget(Name alias, Table<BizNoticeTargetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BizNoticeTarget(Name alias, Table<BizNoticeTargetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("通知目标（多态关联：全员/部门/角色/用户）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.biz_notice_target</code> table reference
     */
    public BizNoticeTarget(String alias) {
        this(DSL.name(alias), BIZ_NOTICE_TARGET);
    }

    /**
     * Create an aliased <code>public.biz_notice_target</code> table reference
     */
    public BizNoticeTarget(Name alias) {
        this(alias, BIZ_NOTICE_TARGET);
    }

    /**
     * Create a <code>public.biz_notice_target</code> table reference
     */
    public BizNoticeTarget() {
        this(DSL.name("biz_notice_target"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTICE_TARGET_NOTICE);
    }

    @Override
    public UniqueKey<BizNoticeTargetRecord> getPrimaryKey() {
        return Keys.BIZ_NOTICE_TARGET_PKEY;
    }

    @Override
    public BizNoticeTarget as(String alias) {
        return new BizNoticeTarget(DSL.name(alias), this);
    }

    @Override
    public BizNoticeTarget as(Name alias) {
        return new BizNoticeTarget(alias, this);
    }

    @Override
    public BizNoticeTarget as(Table<?> alias) {
        return new BizNoticeTarget(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNoticeTarget rename(String name) {
        return new BizNoticeTarget(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNoticeTarget rename(Name name) {
        return new BizNoticeTarget(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BizNoticeTarget rename(Table<?> name) {
        return new BizNoticeTarget(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeTarget where(Condition condition) {
        return new BizNoticeTarget(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeTarget where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeTarget where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeTarget where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeTarget where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeTarget where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeTarget where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BizNoticeTarget where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeTarget whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BizNoticeTarget whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
