/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbConfigRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 系统配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbConfig extends TableImpl<MbConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_config</code>
     */
    public static final MbConfig MB_CONFIG = new MbConfig();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbConfigRecord> getRecordType() {
        return MbConfigRecord.class;
    }

    /**
     * The column <code>public.mb_config.id</code>.
     */
    public final TableField<MbConfigRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_config.tenant_id</code>.
     */
    public final TableField<MbConfigRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_config.config_key</code>.
     */
    public final TableField<MbConfigRecord, String> CONFIG_KEY = createField(DSL.name("config_key"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_config.config_value</code>.
     */
    public final TableField<MbConfigRecord, String> CONFIG_VALUE = createField(DSL.name("config_value"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_config.config_type</code>.
     */
    public final TableField<MbConfigRecord, String> CONFIG_TYPE = createField(DSL.name("config_type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_config.remark</code>.
     */
    public final TableField<MbConfigRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_config.version</code>.
     */
    public final TableField<MbConfigRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_config.created_by</code>.
     */
    public final TableField<MbConfigRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_config.created_at</code>.
     */
    public final TableField<MbConfigRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_config.updated_by</code>.
     */
    public final TableField<MbConfigRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_config.updated_at</code>.
     */
    public final TableField<MbConfigRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbConfig(Name alias, Table<MbConfigRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbConfig(Name alias, Table<MbConfigRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("系统配置表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_config</code> table reference
     */
    public MbConfig(String alias) {
        this(DSL.name(alias), MB_CONFIG);
    }

    /**
     * Create an aliased <code>public.mb_config</code> table reference
     */
    public MbConfig(Name alias) {
        this(alias, MB_CONFIG);
    }

    /**
     * Create a <code>public.mb_config</code> table reference
     */
    public MbConfig() {
        this(DSL.name("mb_config"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UK_CONFIG_TENANT_KEY);
    }

    @Override
    public UniqueKey<MbConfigRecord> getPrimaryKey() {
        return Keys.MB_CONFIG_PKEY;
    }

    @Override
    public MbConfig as(String alias) {
        return new MbConfig(DSL.name(alias), this);
    }

    @Override
    public MbConfig as(Name alias) {
        return new MbConfig(alias, this);
    }

    @Override
    public MbConfig as(Table<?> alias) {
        return new MbConfig(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbConfig rename(String name) {
        return new MbConfig(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbConfig rename(Name name) {
        return new MbConfig(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbConfig rename(Table<?> name) {
        return new MbConfig(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbConfig where(Condition condition) {
        return new MbConfig(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbConfig where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbConfig where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbConfig where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbConfig where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbConfig where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbConfig where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbConfig where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbConfig whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbConfig whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
