/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbDictData.MbDictDataPath;
import com.metabuild.schema.tables.records.MbDictTypeRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 字典类型表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictType extends TableImpl<MbDictTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_dict_type</code>
     */
    public static final MbDictType MB_DICT_TYPE = new MbDictType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbDictTypeRecord> getRecordType() {
        return MbDictTypeRecord.class;
    }

    /**
     * The column <code>public.mb_dict_type.id</code>.
     */
    public final TableField<MbDictTypeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_dict_type.tenant_id</code>.
     */
    public final TableField<MbDictTypeRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_dict_type.name</code>.
     */
    public final TableField<MbDictTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_dict_type.code</code>.
     */
    public final TableField<MbDictTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_dict_type.status</code>.
     */
    public final TableField<MbDictTypeRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.mb_dict_type.remark</code>.
     */
    public final TableField<MbDictTypeRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_dict_type.owner_dept_id</code>.
     */
    public final TableField<MbDictTypeRecord, Long> OWNER_DEPT_ID = createField(DSL.name("owner_dept_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_dict_type.version</code>.
     */
    public final TableField<MbDictTypeRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_dict_type.created_by</code>.
     */
    public final TableField<MbDictTypeRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_dict_type.created_at</code>.
     */
    public final TableField<MbDictTypeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_dict_type.updated_by</code>.
     */
    public final TableField<MbDictTypeRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_dict_type.updated_at</code>.
     */
    public final TableField<MbDictTypeRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbDictType(Name alias, Table<MbDictTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbDictType(Name alias, Table<MbDictTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("字典类型表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_dict_type</code> table reference
     */
    public MbDictType(String alias) {
        this(DSL.name(alias), MB_DICT_TYPE);
    }

    /**
     * Create an aliased <code>public.mb_dict_type</code> table reference
     */
    public MbDictType(Name alias) {
        this(alias, MB_DICT_TYPE);
    }

    /**
     * Create a <code>public.mb_dict_type</code> table reference
     */
    public MbDictType() {
        this(DSL.name("mb_dict_type"), null);
    }

    public <O extends Record> MbDictType(Table<O> path, ForeignKey<O, MbDictTypeRecord> childPath, InverseForeignKey<O, MbDictTypeRecord> parentPath) {
        super(path, childPath, parentPath, MB_DICT_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbDictTypePath extends MbDictType implements Path<MbDictTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbDictTypePath(Table<O> path, ForeignKey<O, MbDictTypeRecord> childPath, InverseForeignKey<O, MbDictTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbDictTypePath(Name alias, Table<MbDictTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbDictTypePath as(String alias) {
            return new MbDictTypePath(DSL.name(alias), this);
        }

        @Override
        public MbDictTypePath as(Name alias) {
            return new MbDictTypePath(alias, this);
        }

        @Override
        public MbDictTypePath as(Table<?> alias) {
            return new MbDictTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UK_DICT_TYPE_TENANT_CODE);
    }

    @Override
    public UniqueKey<MbDictTypeRecord> getPrimaryKey() {
        return Keys.MB_DICT_TYPE_PKEY;
    }

    private transient MbDictDataPath _mbDictData;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_dict_data</code> table
     */
    public MbDictDataPath mbDictData() {
        if (_mbDictData == null)
            _mbDictData = new MbDictDataPath(this, null, Keys.MB_DICT_DATA__FK_DICT_DATA_DICT_TYPE.getInverseKey());

        return _mbDictData;
    }

    @Override
    public MbDictType as(String alias) {
        return new MbDictType(DSL.name(alias), this);
    }

    @Override
    public MbDictType as(Name alias) {
        return new MbDictType(alias, this);
    }

    @Override
    public MbDictType as(Table<?> alias) {
        return new MbDictType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictType rename(String name) {
        return new MbDictType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictType rename(Name name) {
        return new MbDictType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbDictType rename(Table<?> name) {
        return new MbDictType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictType where(Condition condition) {
        return new MbDictType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbDictType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbDictType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
