/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbFileMetadataRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 文件元数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbFileMetadata extends TableImpl<MbFileMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_file_metadata</code>
     */
    public static final MbFileMetadata MB_FILE_METADATA = new MbFileMetadata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbFileMetadataRecord> getRecordType() {
        return MbFileMetadataRecord.class;
    }

    /**
     * The column <code>public.mb_file_metadata.id</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.tenant_id</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_file_metadata.original_name</code>.
     */
    public final TableField<MbFileMetadataRecord, String> ORIGINAL_NAME = createField(DSL.name("original_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.stored_name</code>.
     */
    public final TableField<MbFileMetadataRecord, String> STORED_NAME = createField(DSL.name("stored_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.file_path</code>.
     */
    public final TableField<MbFileMetadataRecord, String> FILE_PATH = createField(DSL.name("file_path"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.file_size</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> FILE_SIZE = createField(DSL.name("file_size"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.content_type</code>.
     */
    public final TableField<MbFileMetadataRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_file_metadata.file_extension</code>.
     */
    public final TableField<MbFileMetadataRecord, String> FILE_EXTENSION = createField(DSL.name("file_extension"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.mb_file_metadata.sha256</code>.
     */
    public final TableField<MbFileMetadataRecord, String> SHA256 = createField(DSL.name("sha256"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.mb_file_metadata.uploader_id</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> UPLOADER_ID = createField(DSL.name("uploader_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.owner_dept_id</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> OWNER_DEPT_ID = createField(DSL.name("owner_dept_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_file_metadata.version</code>.
     */
    public final TableField<MbFileMetadataRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_file_metadata.created_by</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.created_at</code>.
     */
    public final TableField<MbFileMetadataRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_file_metadata.updated_by</code>.
     */
    public final TableField<MbFileMetadataRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_file_metadata.updated_at</code>.
     */
    public final TableField<MbFileMetadataRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbFileMetadata(Name alias, Table<MbFileMetadataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbFileMetadata(Name alias, Table<MbFileMetadataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("文件元数据表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_file_metadata</code> table reference
     */
    public MbFileMetadata(String alias) {
        this(DSL.name(alias), MB_FILE_METADATA);
    }

    /**
     * Create an aliased <code>public.mb_file_metadata</code> table reference
     */
    public MbFileMetadata(Name alias) {
        this(alias, MB_FILE_METADATA);
    }

    /**
     * Create a <code>public.mb_file_metadata</code> table reference
     */
    public MbFileMetadata() {
        this(DSL.name("mb_file_metadata"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FILE_SHA256, Indexes.IDX_FILE_UPLOADER);
    }

    @Override
    public UniqueKey<MbFileMetadataRecord> getPrimaryKey() {
        return Keys.MB_FILE_METADATA_PKEY;
    }

    @Override
    public MbFileMetadata as(String alias) {
        return new MbFileMetadata(DSL.name(alias), this);
    }

    @Override
    public MbFileMetadata as(Name alias) {
        return new MbFileMetadata(alias, this);
    }

    @Override
    public MbFileMetadata as(Table<?> alias) {
        return new MbFileMetadata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbFileMetadata rename(String name) {
        return new MbFileMetadata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbFileMetadata rename(Name name) {
        return new MbFileMetadata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbFileMetadata rename(Table<?> name) {
        return new MbFileMetadata(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbFileMetadata where(Condition condition) {
        return new MbFileMetadata(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbFileMetadata where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbFileMetadata where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbFileMetadata where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbFileMetadata where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbFileMetadata where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbFileMetadata where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbFileMetadata where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbFileMetadata whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbFileMetadata whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
