/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamRole.MbIamRolePath;
import com.metabuild.schema.tables.MbIamUser.MbIamUserPath;
import com.metabuild.schema.tables.records.MbIamUserRoleRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户-角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamUserRole extends TableImpl<MbIamUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_user_role</code>
     */
    public static final MbIamUserRole MB_IAM_USER_ROLE = new MbIamUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamUserRoleRecord> getRecordType() {
        return MbIamUserRoleRecord.class;
    }

    /**
     * The column <code>public.mb_iam_user_role.user_id</code>.
     */
    public final TableField<MbIamUserRoleRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_user_role.role_id</code>.
     */
    public final TableField<MbIamUserRoleRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private MbIamUserRole(Name alias, Table<MbIamUserRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamUserRole(Name alias, Table<MbIamUserRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户-角色关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_user_role</code> table reference
     */
    public MbIamUserRole(String alias) {
        this(DSL.name(alias), MB_IAM_USER_ROLE);
    }

    /**
     * Create an aliased <code>public.mb_iam_user_role</code> table reference
     */
    public MbIamUserRole(Name alias) {
        this(alias, MB_IAM_USER_ROLE);
    }

    /**
     * Create a <code>public.mb_iam_user_role</code> table reference
     */
    public MbIamUserRole() {
        this(DSL.name("mb_iam_user_role"), null);
    }

    public <O extends Record> MbIamUserRole(Table<O> path, ForeignKey<O, MbIamUserRoleRecord> childPath, InverseForeignKey<O, MbIamUserRoleRecord> parentPath) {
        super(path, childPath, parentPath, MB_IAM_USER_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbIamUserRolePath extends MbIamUserRole implements Path<MbIamUserRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbIamUserRolePath(Table<O> path, ForeignKey<O, MbIamUserRoleRecord> childPath, InverseForeignKey<O, MbIamUserRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbIamUserRolePath(Name alias, Table<MbIamUserRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbIamUserRolePath as(String alias) {
            return new MbIamUserRolePath(DSL.name(alias), this);
        }

        @Override
        public MbIamUserRolePath as(Name alias) {
            return new MbIamUserRolePath(alias, this);
        }

        @Override
        public MbIamUserRolePath as(Table<?> alias) {
            return new MbIamUserRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_IAM_USER_ROLE_ROLE_ID);
    }

    @Override
    public UniqueKey<MbIamUserRoleRecord> getPrimaryKey() {
        return Keys.MB_IAM_USER_ROLE_PKEY;
    }

    @Override
    public List<ForeignKey<MbIamUserRoleRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_ROLE, Keys.MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_USER);
    }

    private transient MbIamRolePath _mbIamRole;

    /**
     * Get the implicit join path to the <code>public.mb_iam_role</code> table.
     */
    public MbIamRolePath mbIamRole() {
        if (_mbIamRole == null)
            _mbIamRole = new MbIamRolePath(this, Keys.MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_ROLE, null);

        return _mbIamRole;
    }

    private transient MbIamUserPath _mbIamUser;

    /**
     * Get the implicit join path to the <code>public.mb_iam_user</code> table.
     */
    public MbIamUserPath mbIamUser() {
        if (_mbIamUser == null)
            _mbIamUser = new MbIamUserPath(this, Keys.MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_USER, null);

        return _mbIamUser;
    }

    @Override
    public MbIamUserRole as(String alias) {
        return new MbIamUserRole(DSL.name(alias), this);
    }

    @Override
    public MbIamUserRole as(Name alias) {
        return new MbIamUserRole(alias, this);
    }

    @Override
    public MbIamUserRole as(Table<?> alias) {
        return new MbIamUserRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamUserRole rename(String name) {
        return new MbIamUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamUserRole rename(Name name) {
        return new MbIamUserRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamUserRole rename(Table<?> name) {
        return new MbIamUserRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Condition condition) {
        return new MbIamUserRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
