/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamDept.MbIamDeptPath;
import com.metabuild.schema.tables.MbIamMenu.MbIamMenuPath;
import com.metabuild.schema.tables.MbIamRoleDataScopeDept.MbIamRoleDataScopeDeptPath;
import com.metabuild.schema.tables.MbIamRoleMenu.MbIamRoleMenuPath;
import com.metabuild.schema.tables.MbIamUser.MbIamUserPath;
import com.metabuild.schema.tables.MbIamUserRole.MbIamUserRolePath;
import com.metabuild.schema.tables.records.MbIamRoleRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRole extends TableImpl<MbIamRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_role</code>
     */
    public static final MbIamRole MB_IAM_ROLE = new MbIamRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamRoleRecord> getRecordType() {
        return MbIamRoleRecord.class;
    }

    /**
     * The column <code>public.mb_iam_role.id</code>.
     */
    public final TableField<MbIamRoleRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role.tenant_id</code>.
     */
    public final TableField<MbIamRoleRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_role.name</code>.
     */
    public final TableField<MbIamRoleRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role.code</code>.
     */
    public final TableField<MbIamRoleRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role.sort_order</code>.
     */
    public final TableField<MbIamRoleRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_role.status</code>.
     */
    public final TableField<MbIamRoleRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.mb_iam_role.data_scope</code>.
     * 数据权限范围：ALL/CUSTOM_DEPT/OWN_DEPT/OWN_DEPT_AND_CHILD/SELF
     */
    public final TableField<MbIamRoleRecord, String> DATA_SCOPE = createField(DSL.name("data_scope"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'SELF'::character varying"), SQLDataType.VARCHAR)), this, "数据权限范围：ALL/CUSTOM_DEPT/OWN_DEPT/OWN_DEPT_AND_CHILD/SELF");

    /**
     * The column <code>public.mb_iam_role.remark</code>.
     */
    public final TableField<MbIamRoleRecord, String> REMARK = createField(DSL.name("remark"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_iam_role.owner_dept_id</code>.
     */
    public final TableField<MbIamRoleRecord, Long> OWNER_DEPT_ID = createField(DSL.name("owner_dept_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_role.version</code>.
     */
    public final TableField<MbIamRoleRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_role.created_by</code>.
     */
    public final TableField<MbIamRoleRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role.created_at</code>.
     */
    public final TableField<MbIamRoleRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_iam_role.updated_by</code>.
     */
    public final TableField<MbIamRoleRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role.updated_at</code>.
     */
    public final TableField<MbIamRoleRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbIamRole(Name alias, Table<MbIamRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamRole(Name alias, Table<MbIamRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("角色表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_role</code> table reference
     */
    public MbIamRole(String alias) {
        this(DSL.name(alias), MB_IAM_ROLE);
    }

    /**
     * Create an aliased <code>public.mb_iam_role</code> table reference
     */
    public MbIamRole(Name alias) {
        this(alias, MB_IAM_ROLE);
    }

    /**
     * Create a <code>public.mb_iam_role</code> table reference
     */
    public MbIamRole() {
        this(DSL.name("mb_iam_role"), null);
    }

    public <O extends Record> MbIamRole(Table<O> path, ForeignKey<O, MbIamRoleRecord> childPath, InverseForeignKey<O, MbIamRoleRecord> parentPath) {
        super(path, childPath, parentPath, MB_IAM_ROLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbIamRolePath extends MbIamRole implements Path<MbIamRoleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbIamRolePath(Table<O> path, ForeignKey<O, MbIamRoleRecord> childPath, InverseForeignKey<O, MbIamRoleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbIamRolePath(Name alias, Table<MbIamRoleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbIamRolePath as(String alias) {
            return new MbIamRolePath(DSL.name(alias), this);
        }

        @Override
        public MbIamRolePath as(Name alias) {
            return new MbIamRolePath(alias, this);
        }

        @Override
        public MbIamRolePath as(Table<?> alias) {
            return new MbIamRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UK_IAM_ROLE_TENANT_CODE);
    }

    @Override
    public UniqueKey<MbIamRoleRecord> getPrimaryKey() {
        return Keys.MB_IAM_ROLE_PKEY;
    }

    private transient MbIamRoleDataScopeDeptPath _mbIamRoleDataScopeDept;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_iam_role_data_scope_dept</code> table
     */
    public MbIamRoleDataScopeDeptPath mbIamRoleDataScopeDept() {
        if (_mbIamRoleDataScopeDept == null)
            _mbIamRoleDataScopeDept = new MbIamRoleDataScopeDeptPath(this, null, Keys.MB_IAM_ROLE_DATA_SCOPE_DEPT__FK_IAM_ROLE_DSD_ROLE.getInverseKey());

        return _mbIamRoleDataScopeDept;
    }

    private transient MbIamRoleMenuPath _mbIamRoleMenu;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_iam_role_menu</code> table
     */
    public MbIamRoleMenuPath mbIamRoleMenu() {
        if (_mbIamRoleMenu == null)
            _mbIamRoleMenu = new MbIamRoleMenuPath(this, null, Keys.MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_ROLE.getInverseKey());

        return _mbIamRoleMenu;
    }

    private transient MbIamUserRolePath _mbIamUserRole;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_iam_user_role</code> table
     */
    public MbIamUserRolePath mbIamUserRole() {
        if (_mbIamUserRole == null)
            _mbIamUserRole = new MbIamUserRolePath(this, null, Keys.MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_ROLE.getInverseKey());

        return _mbIamUserRole;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_iam_dept</code> table
     */
    public MbIamDeptPath mbIamDept() {
        return mbIamRoleDataScopeDept().mbIamDept();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_iam_menu</code> table
     */
    public MbIamMenuPath mbIamMenu() {
        return mbIamRoleMenu().mbIamMenu();
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_iam_user</code> table
     */
    public MbIamUserPath mbIamUser() {
        return mbIamUserRole().mbIamUser();
    }

    @Override
    public List<Check<MbIamRoleRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_iam_role_data_scope"), "(((data_scope)::text = ANY ((ARRAY['ALL'::character varying, 'OWN_DEPT'::character varying, 'OWN_DEPT_AND_CHILD'::character varying, 'CUSTOM_DEPT'::character varying, 'SELF'::character varying])::text[])))", true),
            Internal.createCheck(this, DSL.name("chk_iam_role_status"), "((status = ANY (ARRAY[0, 1])))", true)
        );
    }

    @Override
    public MbIamRole as(String alias) {
        return new MbIamRole(DSL.name(alias), this);
    }

    @Override
    public MbIamRole as(Name alias) {
        return new MbIamRole(alias, this);
    }

    @Override
    public MbIamRole as(Table<?> alias) {
        return new MbIamRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRole rename(String name) {
        return new MbIamRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRole rename(Name name) {
        return new MbIamRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRole rename(Table<?> name) {
        return new MbIamRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRole where(Condition condition) {
        return new MbIamRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
