/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamUser.MbIamUserPath;
import com.metabuild.schema.tables.records.MbIamLoginLogRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 登录日志
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamLoginLog extends TableImpl<MbIamLoginLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_login_log</code>
     */
    public static final MbIamLoginLog MB_IAM_LOGIN_LOG = new MbIamLoginLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamLoginLogRecord> getRecordType() {
        return MbIamLoginLogRecord.class;
    }

    /**
     * The column <code>public.mb_iam_login_log.id</code>.
     */
    public final TableField<MbIamLoginLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_login_log.user_id</code>.
     */
    public final TableField<MbIamLoginLogRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_iam_login_log.username</code>.
     */
    public final TableField<MbIamLoginLogRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_login_log.login_ip</code>.
     */
    public final TableField<MbIamLoginLogRecord, String> LOGIN_IP = createField(DSL.name("login_ip"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.mb_iam_login_log.user_agent</code>.
     */
    public final TableField<MbIamLoginLogRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_iam_login_log.success</code>.
     */
    public final TableField<MbIamLoginLogRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_login_log.failure_reason</code>.
     */
    public final TableField<MbIamLoginLogRecord, String> FAILURE_REASON = createField(DSL.name("failure_reason"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_iam_login_log.created_at</code>.
     */
    public final TableField<MbIamLoginLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbIamLoginLog(Name alias, Table<MbIamLoginLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamLoginLog(Name alias, Table<MbIamLoginLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("登录日志"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_login_log</code> table reference
     */
    public MbIamLoginLog(String alias) {
        this(DSL.name(alias), MB_IAM_LOGIN_LOG);
    }

    /**
     * Create an aliased <code>public.mb_iam_login_log</code> table reference
     */
    public MbIamLoginLog(Name alias) {
        this(alias, MB_IAM_LOGIN_LOG);
    }

    /**
     * Create a <code>public.mb_iam_login_log</code> table reference
     */
    public MbIamLoginLog() {
        this(DSL.name("mb_iam_login_log"), null);
    }

    public <O extends Record> MbIamLoginLog(Table<O> path, ForeignKey<O, MbIamLoginLogRecord> childPath, InverseForeignKey<O, MbIamLoginLogRecord> parentPath) {
        super(path, childPath, parentPath, MB_IAM_LOGIN_LOG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbIamLoginLogPath extends MbIamLoginLog implements Path<MbIamLoginLogRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbIamLoginLogPath(Table<O> path, ForeignKey<O, MbIamLoginLogRecord> childPath, InverseForeignKey<O, MbIamLoginLogRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbIamLoginLogPath(Name alias, Table<MbIamLoginLogRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbIamLoginLogPath as(String alias) {
            return new MbIamLoginLogPath(DSL.name(alias), this);
        }

        @Override
        public MbIamLoginLogPath as(Name alias) {
            return new MbIamLoginLogPath(alias, this);
        }

        @Override
        public MbIamLoginLogPath as(Table<?> alias) {
            return new MbIamLoginLogPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_IAM_LOGIN_LOG_USER_ID, Indexes.IDX_LOGIN_LOG_TIME, Indexes.IDX_LOGIN_LOG_USER);
    }

    @Override
    public UniqueKey<MbIamLoginLogRecord> getPrimaryKey() {
        return Keys.MB_IAM_LOGIN_LOG_PKEY;
    }

    @Override
    public List<ForeignKey<MbIamLoginLogRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_IAM_LOGIN_LOG__FK_IAM_LOGIN_LOG_USER);
    }

    private transient MbIamUserPath _mbIamUser;

    /**
     * Get the implicit join path to the <code>public.mb_iam_user</code> table.
     */
    public MbIamUserPath mbIamUser() {
        if (_mbIamUser == null)
            _mbIamUser = new MbIamUserPath(this, Keys.MB_IAM_LOGIN_LOG__FK_IAM_LOGIN_LOG_USER, null);

        return _mbIamUser;
    }

    @Override
    public MbIamLoginLog as(String alias) {
        return new MbIamLoginLog(DSL.name(alias), this);
    }

    @Override
    public MbIamLoginLog as(Name alias) {
        return new MbIamLoginLog(alias, this);
    }

    @Override
    public MbIamLoginLog as(Table<?> alias) {
        return new MbIamLoginLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamLoginLog rename(String name) {
        return new MbIamLoginLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamLoginLog rename(Name name) {
        return new MbIamLoginLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamLoginLog rename(Table<?> name) {
        return new MbIamLoginLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamLoginLog where(Condition condition) {
        return new MbIamLoginLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamLoginLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamLoginLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamLoginLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamLoginLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamLoginLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamLoginLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamLoginLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamLoginLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamLoginLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
