/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbIamMenuRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamMenu extends TableImpl<MbIamMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_menu</code>
     */
    public static final MbIamMenu MB_IAM_MENU = new MbIamMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamMenuRecord> getRecordType() {
        return MbIamMenuRecord.class;
    }

    /**
     * The column <code>public.mb_iam_menu.id</code>.
     */
    public final TableField<MbIamMenuRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_menu.tenant_id</code>.
     */
    public final TableField<MbIamMenuRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_menu.parent_id</code>.
     */
    public final TableField<MbIamMenuRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_menu.name</code>.
     */
    public final TableField<MbIamMenuRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_menu.permission_code</code>.
     */
    public final TableField<MbIamMenuRecord, String> PERMISSION_CODE = createField(DSL.name("permission_code"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_iam_menu.menu_type</code>.
     */
    public final TableField<MbIamMenuRecord, String> MENU_TYPE = createField(DSL.name("menu_type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'MENU'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_iam_menu.icon</code>.
     */
    public final TableField<MbIamMenuRecord, String> ICON = createField(DSL.name("icon"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_iam_menu.sort_order</code>.
     */
    public final TableField<MbIamMenuRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_menu.visible</code>.
     */
    public final TableField<MbIamMenuRecord, Boolean> VISIBLE = createField(DSL.name("visible"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_iam_menu.version</code>.
     */
    public final TableField<MbIamMenuRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_menu.created_by</code>.
     */
    public final TableField<MbIamMenuRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_menu.created_at</code>.
     */
    public final TableField<MbIamMenuRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_iam_menu.updated_by</code>.
     */
    public final TableField<MbIamMenuRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_menu.updated_at</code>.
     */
    public final TableField<MbIamMenuRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbIamMenu(Name alias, Table<MbIamMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamMenu(Name alias, Table<MbIamMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("菜单表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_menu</code> table reference
     */
    public MbIamMenu(String alias) {
        this(DSL.name(alias), MB_IAM_MENU);
    }

    /**
     * Create an aliased <code>public.mb_iam_menu</code> table reference
     */
    public MbIamMenu(Name alias) {
        this(alias, MB_IAM_MENU);
    }

    /**
     * Create a <code>public.mb_iam_menu</code> table reference
     */
    public MbIamMenu() {
        this(DSL.name("mb_iam_menu"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_IAM_MENU_PARENT);
    }

    @Override
    public UniqueKey<MbIamMenuRecord> getPrimaryKey() {
        return Keys.MB_IAM_MENU_PKEY;
    }

    @Override
    public MbIamMenu as(String alias) {
        return new MbIamMenu(DSL.name(alias), this);
    }

    @Override
    public MbIamMenu as(Name alias) {
        return new MbIamMenu(alias, this);
    }

    @Override
    public MbIamMenu as(Table<?> alias) {
        return new MbIamMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamMenu rename(String name) {
        return new MbIamMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamMenu rename(Name name) {
        return new MbIamMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamMenu rename(Table<?> name) {
        return new MbIamMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamMenu where(Condition condition) {
        return new MbIamMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
