/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamMenu.MbIamMenuPath;
import com.metabuild.schema.tables.MbIamRole.MbIamRolePath;
import com.metabuild.schema.tables.records.MbIamRoleMenuRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 角色-菜单关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRoleMenu extends TableImpl<MbIamRoleMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_role_menu</code>
     */
    public static final MbIamRoleMenu MB_IAM_ROLE_MENU = new MbIamRoleMenu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamRoleMenuRecord> getRecordType() {
        return MbIamRoleMenuRecord.class;
    }

    /**
     * The column <code>public.mb_iam_role_menu.role_id</code>.
     */
    public final TableField<MbIamRoleMenuRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role_menu.menu_id</code>.
     */
    public final TableField<MbIamRoleMenuRecord, Long> MENU_ID = createField(DSL.name("menu_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private MbIamRoleMenu(Name alias, Table<MbIamRoleMenuRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamRoleMenu(Name alias, Table<MbIamRoleMenuRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("角色-菜单关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_role_menu</code> table reference
     */
    public MbIamRoleMenu(String alias) {
        this(DSL.name(alias), MB_IAM_ROLE_MENU);
    }

    /**
     * Create an aliased <code>public.mb_iam_role_menu</code> table reference
     */
    public MbIamRoleMenu(Name alias) {
        this(alias, MB_IAM_ROLE_MENU);
    }

    /**
     * Create a <code>public.mb_iam_role_menu</code> table reference
     */
    public MbIamRoleMenu() {
        this(DSL.name("mb_iam_role_menu"), null);
    }

    public <O extends Record> MbIamRoleMenu(Table<O> path, ForeignKey<O, MbIamRoleMenuRecord> childPath, InverseForeignKey<O, MbIamRoleMenuRecord> parentPath) {
        super(path, childPath, parentPath, MB_IAM_ROLE_MENU);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbIamRoleMenuPath extends MbIamRoleMenu implements Path<MbIamRoleMenuRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbIamRoleMenuPath(Table<O> path, ForeignKey<O, MbIamRoleMenuRecord> childPath, InverseForeignKey<O, MbIamRoleMenuRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbIamRoleMenuPath(Name alias, Table<MbIamRoleMenuRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbIamRoleMenuPath as(String alias) {
            return new MbIamRoleMenuPath(DSL.name(alias), this);
        }

        @Override
        public MbIamRoleMenuPath as(Name alias) {
            return new MbIamRoleMenuPath(alias, this);
        }

        @Override
        public MbIamRoleMenuPath as(Table<?> alias) {
            return new MbIamRoleMenuPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbIamRoleMenuRecord> getPrimaryKey() {
        return Keys.MB_IAM_ROLE_MENU_PKEY;
    }

    @Override
    public List<ForeignKey<MbIamRoleMenuRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_MENU, Keys.MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_ROLE);
    }

    private transient MbIamMenuPath _mbIamMenu;

    /**
     * Get the implicit join path to the <code>public.mb_iam_menu</code> table.
     */
    public MbIamMenuPath mbIamMenu() {
        if (_mbIamMenu == null)
            _mbIamMenu = new MbIamMenuPath(this, Keys.MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_MENU, null);

        return _mbIamMenu;
    }

    private transient MbIamRolePath _mbIamRole;

    /**
     * Get the implicit join path to the <code>public.mb_iam_role</code> table.
     */
    public MbIamRolePath mbIamRole() {
        if (_mbIamRole == null)
            _mbIamRole = new MbIamRolePath(this, Keys.MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_ROLE, null);

        return _mbIamRole;
    }

    @Override
    public MbIamRoleMenu as(String alias) {
        return new MbIamRoleMenu(DSL.name(alias), this);
    }

    @Override
    public MbIamRoleMenu as(Name alias) {
        return new MbIamRoleMenu(alias, this);
    }

    @Override
    public MbIamRoleMenu as(Table<?> alias) {
        return new MbIamRoleMenu(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRoleMenu rename(String name) {
        return new MbIamRoleMenu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRoleMenu rename(Name name) {
        return new MbIamRoleMenu(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRoleMenu rename(Table<?> name) {
        return new MbIamRoleMenu(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleMenu where(Condition condition) {
        return new MbIamRoleMenu(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleMenu where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleMenu where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleMenu where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleMenu where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleMenu where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleMenu where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleMenu where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleMenu whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleMenu whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
