/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamDept.MbIamDeptPath;
import com.metabuild.schema.tables.MbIamRole.MbIamRolePath;
import com.metabuild.schema.tables.MbIamRoleDataScopeDept.MbIamRoleDataScopeDeptPath;
import com.metabuild.schema.tables.MbIamUser.MbIamUserPath;
import com.metabuild.schema.tables.records.MbIamDeptRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 部门表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamDept extends TableImpl<MbIamDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_dept</code>
     */
    public static final MbIamDept MB_IAM_DEPT = new MbIamDept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamDeptRecord> getRecordType() {
        return MbIamDeptRecord.class;
    }

    /**
     * The column <code>public.mb_iam_dept.id</code>.
     */
    public final TableField<MbIamDeptRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_dept.tenant_id</code>.
     */
    public final TableField<MbIamDeptRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_dept.parent_id</code>.
     */
    public final TableField<MbIamDeptRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_iam_dept.name</code>.
     */
    public final TableField<MbIamDeptRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_dept.sort_order</code>.
     */
    public final TableField<MbIamDeptRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_dept.status</code>.
     */
    public final TableField<MbIamDeptRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.mb_iam_dept.leader_user_id</code>.
     */
    public final TableField<MbIamDeptRecord, Long> LEADER_USER_ID = createField(DSL.name("leader_user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_iam_dept.owner_dept_id</code>.
     */
    public final TableField<MbIamDeptRecord, Long> OWNER_DEPT_ID = createField(DSL.name("owner_dept_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_dept.version</code>.
     */
    public final TableField<MbIamDeptRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_dept.created_by</code>.
     */
    public final TableField<MbIamDeptRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_dept.created_at</code>.
     */
    public final TableField<MbIamDeptRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_iam_dept.updated_by</code>.
     */
    public final TableField<MbIamDeptRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_dept.updated_at</code>.
     */
    public final TableField<MbIamDeptRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbIamDept(Name alias, Table<MbIamDeptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamDept(Name alias, Table<MbIamDeptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("部门表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_dept</code> table reference
     */
    public MbIamDept(String alias) {
        this(DSL.name(alias), MB_IAM_DEPT);
    }

    /**
     * Create an aliased <code>public.mb_iam_dept</code> table reference
     */
    public MbIamDept(Name alias) {
        this(alias, MB_IAM_DEPT);
    }

    /**
     * Create a <code>public.mb_iam_dept</code> table reference
     */
    public MbIamDept() {
        this(DSL.name("mb_iam_dept"), null);
    }

    public <O extends Record> MbIamDept(Table<O> path, ForeignKey<O, MbIamDeptRecord> childPath, InverseForeignKey<O, MbIamDeptRecord> parentPath) {
        super(path, childPath, parentPath, MB_IAM_DEPT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbIamDeptPath extends MbIamDept implements Path<MbIamDeptRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbIamDeptPath(Table<O> path, ForeignKey<O, MbIamDeptRecord> childPath, InverseForeignKey<O, MbIamDeptRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbIamDeptPath(Name alias, Table<MbIamDeptRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbIamDeptPath as(String alias) {
            return new MbIamDeptPath(DSL.name(alias), this);
        }

        @Override
        public MbIamDeptPath as(Name alias) {
            return new MbIamDeptPath(alias, this);
        }

        @Override
        public MbIamDeptPath as(Table<?> alias) {
            return new MbIamDeptPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_IAM_DEPT_PARENT);
    }

    @Override
    public UniqueKey<MbIamDeptRecord> getPrimaryKey() {
        return Keys.MB_IAM_DEPT_PKEY;
    }

    @Override
    public List<ForeignKey<MbIamDeptRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_IAM_DEPT__FK_IAM_DEPT_LEADER, Keys.MB_IAM_DEPT__FK_IAM_DEPT_PARENT);
    }

    private transient MbIamUserPath _mbIamUser;

    /**
     * Get the implicit join path to the <code>public.mb_iam_user</code> table.
     */
    public MbIamUserPath mbIamUser() {
        if (_mbIamUser == null)
            _mbIamUser = new MbIamUserPath(this, Keys.MB_IAM_DEPT__FK_IAM_DEPT_LEADER, null);

        return _mbIamUser;
    }

    private transient MbIamDeptPath _mbIamDept;

    /**
     * Get the implicit join path to the <code>public.mb_iam_dept</code> table.
     */
    public MbIamDeptPath mbIamDept() {
        if (_mbIamDept == null)
            _mbIamDept = new MbIamDeptPath(this, Keys.MB_IAM_DEPT__FK_IAM_DEPT_PARENT, null);

        return _mbIamDept;
    }

    private transient MbIamRoleDataScopeDeptPath _mbIamRoleDataScopeDept;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_iam_role_data_scope_dept</code> table
     */
    public MbIamRoleDataScopeDeptPath mbIamRoleDataScopeDept() {
        if (_mbIamRoleDataScopeDept == null)
            _mbIamRoleDataScopeDept = new MbIamRoleDataScopeDeptPath(this, null, Keys.MB_IAM_ROLE_DATA_SCOPE_DEPT__FK_IAM_ROLE_DSD_DEPT.getInverseKey());

        return _mbIamRoleDataScopeDept;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.mb_iam_role</code> table
     */
    public MbIamRolePath mbIamRole() {
        return mbIamRoleDataScopeDept().mbIamRole();
    }

    @Override
    public List<Check<MbIamDeptRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_iam_dept_status"), "((status = ANY (ARRAY[0, 1])))", true)
        );
    }

    @Override
    public MbIamDept as(String alias) {
        return new MbIamDept(DSL.name(alias), this);
    }

    @Override
    public MbIamDept as(Name alias) {
        return new MbIamDept(alias, this);
    }

    @Override
    public MbIamDept as(Table<?> alias) {
        return new MbIamDept(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamDept rename(String name) {
        return new MbIamDept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamDept rename(Name name) {
        return new MbIamDept(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamDept rename(Table<?> name) {
        return new MbIamDept(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamDept where(Condition condition) {
        return new MbIamDept(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamDept where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamDept where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamDept where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamDept where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamDept where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamDept where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamDept where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamDept whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamDept whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
