/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbIamPasswordHistoryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 密码历史表（防重用）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamPasswordHistory extends TableImpl<MbIamPasswordHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_password_history</code>
     */
    public static final MbIamPasswordHistory MB_IAM_PASSWORD_HISTORY = new MbIamPasswordHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamPasswordHistoryRecord> getRecordType() {
        return MbIamPasswordHistoryRecord.class;
    }

    /**
     * The column <code>public.mb_iam_password_history.id</code>.
     */
    public final TableField<MbIamPasswordHistoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_password_history.user_id</code>.
     */
    public final TableField<MbIamPasswordHistoryRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_password_history.password_hash</code>.
     */
    public final TableField<MbIamPasswordHistoryRecord, String> PASSWORD_HASH = createField(DSL.name("password_hash"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_password_history.created_at</code>.
     */
    public final TableField<MbIamPasswordHistoryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbIamPasswordHistory(Name alias, Table<MbIamPasswordHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamPasswordHistory(Name alias, Table<MbIamPasswordHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("密码历史表（防重用）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_password_history</code> table
     * reference
     */
    public MbIamPasswordHistory(String alias) {
        this(DSL.name(alias), MB_IAM_PASSWORD_HISTORY);
    }

    /**
     * Create an aliased <code>public.mb_iam_password_history</code> table
     * reference
     */
    public MbIamPasswordHistory(Name alias) {
        this(alias, MB_IAM_PASSWORD_HISTORY);
    }

    /**
     * Create a <code>public.mb_iam_password_history</code> table reference
     */
    public MbIamPasswordHistory() {
        this(DSL.name("mb_iam_password_history"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PASSWORD_HISTORY_USER);
    }

    @Override
    public UniqueKey<MbIamPasswordHistoryRecord> getPrimaryKey() {
        return Keys.MB_IAM_PASSWORD_HISTORY_PKEY;
    }

    @Override
    public MbIamPasswordHistory as(String alias) {
        return new MbIamPasswordHistory(DSL.name(alias), this);
    }

    @Override
    public MbIamPasswordHistory as(Name alias) {
        return new MbIamPasswordHistory(alias, this);
    }

    @Override
    public MbIamPasswordHistory as(Table<?> alias) {
        return new MbIamPasswordHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamPasswordHistory rename(String name) {
        return new MbIamPasswordHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamPasswordHistory rename(Name name) {
        return new MbIamPasswordHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamPasswordHistory rename(Table<?> name) {
        return new MbIamPasswordHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamPasswordHistory where(Condition condition) {
        return new MbIamPasswordHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamPasswordHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamPasswordHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamPasswordHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamPasswordHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamPasswordHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamPasswordHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamPasswordHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamPasswordHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamPasswordHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
