/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbIamUserRoleRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 用户-角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamUserRole extends TableImpl<MbIamUserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_user_role</code>
     */
    public static final MbIamUserRole MB_IAM_USER_ROLE = new MbIamUserRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamUserRoleRecord> getRecordType() {
        return MbIamUserRoleRecord.class;
    }

    /**
     * The column <code>public.mb_iam_user_role.user_id</code>.
     */
    public final TableField<MbIamUserRoleRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_user_role.role_id</code>.
     */
    public final TableField<MbIamUserRoleRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private MbIamUserRole(Name alias, Table<MbIamUserRoleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamUserRole(Name alias, Table<MbIamUserRoleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("用户-角色关联表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_user_role</code> table reference
     */
    public MbIamUserRole(String alias) {
        this(DSL.name(alias), MB_IAM_USER_ROLE);
    }

    /**
     * Create an aliased <code>public.mb_iam_user_role</code> table reference
     */
    public MbIamUserRole(Name alias) {
        this(alias, MB_IAM_USER_ROLE);
    }

    /**
     * Create a <code>public.mb_iam_user_role</code> table reference
     */
    public MbIamUserRole() {
        this(DSL.name("mb_iam_user_role"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbIamUserRoleRecord> getPrimaryKey() {
        return Keys.MB_IAM_USER_ROLE_PKEY;
    }

    @Override
    public MbIamUserRole as(String alias) {
        return new MbIamUserRole(DSL.name(alias), this);
    }

    @Override
    public MbIamUserRole as(Name alias) {
        return new MbIamUserRole(alias, this);
    }

    @Override
    public MbIamUserRole as(Table<?> alias) {
        return new MbIamUserRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamUserRole rename(String name) {
        return new MbIamUserRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamUserRole rename(Name name) {
        return new MbIamUserRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamUserRole rename(Table<?> name) {
        return new MbIamUserRole(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Condition condition) {
        return new MbIamUserRole(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamUserRole where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamUserRole whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
