/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamRouteTree.MbIamRouteTreePath;
import com.metabuild.schema.tables.records.MbIamRouteTreeRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 路由树
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRouteTree extends TableImpl<MbIamRouteTreeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_route_tree</code>
     */
    public static final MbIamRouteTree MB_IAM_ROUTE_TREE = new MbIamRouteTree();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamRouteTreeRecord> getRecordType() {
        return MbIamRouteTreeRecord.class;
    }

    /**
     * The column <code>public.mb_iam_route_tree.id</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.tenant_id</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.parent_id</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Long> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_iam_route_tree.path</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.name</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.component</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> COMPONENT = createField(DSL.name("component"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.redirect</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> REDIRECT = createField(DSL.name("redirect"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.icon</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> ICON = createField(DSL.name("icon"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.sort_order</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.hidden</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Boolean> HIDDEN = createField(DSL.name("hidden"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.permission_code</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> PERMISSION_CODE = createField(DSL.name("permission_code"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.route_type</code>.
     */
    public final TableField<MbIamRouteTreeRecord, String> ROUTE_TYPE = createField(DSL.name("route_type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'MENU'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.version</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.created_by</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.created_at</code>.
     */
    public final TableField<MbIamRouteTreeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.updated_by</code>.
     */
    public final TableField<MbIamRouteTreeRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_route_tree.updated_at</code>.
     */
    public final TableField<MbIamRouteTreeRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbIamRouteTree(Name alias, Table<MbIamRouteTreeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamRouteTree(Name alias, Table<MbIamRouteTreeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("路由树"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_route_tree</code> table reference
     */
    public MbIamRouteTree(String alias) {
        this(DSL.name(alias), MB_IAM_ROUTE_TREE);
    }

    /**
     * Create an aliased <code>public.mb_iam_route_tree</code> table reference
     */
    public MbIamRouteTree(Name alias) {
        this(alias, MB_IAM_ROUTE_TREE);
    }

    /**
     * Create a <code>public.mb_iam_route_tree</code> table reference
     */
    public MbIamRouteTree() {
        this(DSL.name("mb_iam_route_tree"), null);
    }

    public <O extends Record> MbIamRouteTree(Table<O> path, ForeignKey<O, MbIamRouteTreeRecord> childPath, InverseForeignKey<O, MbIamRouteTreeRecord> parentPath) {
        super(path, childPath, parentPath, MB_IAM_ROUTE_TREE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbIamRouteTreePath extends MbIamRouteTree implements Path<MbIamRouteTreeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbIamRouteTreePath(Table<O> path, ForeignKey<O, MbIamRouteTreeRecord> childPath, InverseForeignKey<O, MbIamRouteTreeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbIamRouteTreePath(Name alias, Table<MbIamRouteTreeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbIamRouteTreePath as(String alias) {
            return new MbIamRouteTreePath(DSL.name(alias), this);
        }

        @Override
        public MbIamRouteTreePath as(Name alias) {
            return new MbIamRouteTreePath(alias, this);
        }

        @Override
        public MbIamRouteTreePath as(Table<?> alias) {
            return new MbIamRouteTreePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ROUTE_TREE_PARENT);
    }

    @Override
    public UniqueKey<MbIamRouteTreeRecord> getPrimaryKey() {
        return Keys.MB_IAM_ROUTE_TREE_PKEY;
    }

    @Override
    public List<ForeignKey<MbIamRouteTreeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_IAM_ROUTE_TREE__FK_IAM_ROUTE_TREE_PARENT);
    }

    private transient MbIamRouteTreePath _mbIamRouteTree;

    /**
     * Get the implicit join path to the <code>public.mb_iam_route_tree</code>
     * table.
     */
    public MbIamRouteTreePath mbIamRouteTree() {
        if (_mbIamRouteTree == null)
            _mbIamRouteTree = new MbIamRouteTreePath(this, Keys.MB_IAM_ROUTE_TREE__FK_IAM_ROUTE_TREE_PARENT, null);

        return _mbIamRouteTree;
    }

    @Override
    public List<Check<MbIamRouteTreeRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_iam_route_tree_route_type"), "(((route_type)::text = ANY ((ARRAY['LAYOUT'::character varying, 'PAGE'::character varying, 'MENU'::character varying, 'BUTTON'::character varying, 'EXTERNAL'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbIamRouteTree as(String alias) {
        return new MbIamRouteTree(DSL.name(alias), this);
    }

    @Override
    public MbIamRouteTree as(Name alias) {
        return new MbIamRouteTree(alias, this);
    }

    @Override
    public MbIamRouteTree as(Table<?> alias) {
        return new MbIamRouteTree(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRouteTree rename(String name) {
        return new MbIamRouteTree(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRouteTree rename(Name name) {
        return new MbIamRouteTree(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRouteTree rename(Table<?> name) {
        return new MbIamRouteTree(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRouteTree where(Condition condition) {
        return new MbIamRouteTree(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRouteTree where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRouteTree where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRouteTree where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRouteTree where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRouteTree where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRouteTree where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRouteTree where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRouteTree whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRouteTree whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
