/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbIamRoleDataScopeDeptRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 角色-数据权限自定义部门关联表（CUSTOM_DEPT 时使用）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRoleDataScopeDept extends TableImpl<MbIamRoleDataScopeDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_iam_role_data_scope_dept</code>
     */
    public static final MbIamRoleDataScopeDept MB_IAM_ROLE_DATA_SCOPE_DEPT = new MbIamRoleDataScopeDept();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbIamRoleDataScopeDeptRecord> getRecordType() {
        return MbIamRoleDataScopeDeptRecord.class;
    }

    /**
     * The column <code>public.mb_iam_role_data_scope_dept.role_id</code>.
     */
    public final TableField<MbIamRoleDataScopeDeptRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_iam_role_data_scope_dept.dept_id</code>.
     */
    public final TableField<MbIamRoleDataScopeDeptRecord, Long> DEPT_ID = createField(DSL.name("dept_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private MbIamRoleDataScopeDept(Name alias, Table<MbIamRoleDataScopeDeptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbIamRoleDataScopeDept(Name alias, Table<MbIamRoleDataScopeDeptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("角色-数据权限自定义部门关联表（CUSTOM_DEPT 时使用）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_iam_role_data_scope_dept</code> table
     * reference
     */
    public MbIamRoleDataScopeDept(String alias) {
        this(DSL.name(alias), MB_IAM_ROLE_DATA_SCOPE_DEPT);
    }

    /**
     * Create an aliased <code>public.mb_iam_role_data_scope_dept</code> table
     * reference
     */
    public MbIamRoleDataScopeDept(Name alias) {
        this(alias, MB_IAM_ROLE_DATA_SCOPE_DEPT);
    }

    /**
     * Create a <code>public.mb_iam_role_data_scope_dept</code> table reference
     */
    public MbIamRoleDataScopeDept() {
        this(DSL.name("mb_iam_role_data_scope_dept"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbIamRoleDataScopeDeptRecord> getPrimaryKey() {
        return Keys.MB_IAM_ROLE_DATA_SCOPE_DEPT_PKEY;
    }

    @Override
    public MbIamRoleDataScopeDept as(String alias) {
        return new MbIamRoleDataScopeDept(DSL.name(alias), this);
    }

    @Override
    public MbIamRoleDataScopeDept as(Name alias) {
        return new MbIamRoleDataScopeDept(alias, this);
    }

    @Override
    public MbIamRoleDataScopeDept as(Table<?> alias) {
        return new MbIamRoleDataScopeDept(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRoleDataScopeDept rename(String name) {
        return new MbIamRoleDataScopeDept(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRoleDataScopeDept rename(Name name) {
        return new MbIamRoleDataScopeDept(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbIamRoleDataScopeDept rename(Table<?> name) {
        return new MbIamRoleDataScopeDept(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleDataScopeDept where(Condition condition) {
        return new MbIamRoleDataScopeDept(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleDataScopeDept where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleDataScopeDept where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleDataScopeDept where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleDataScopeDept where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleDataScopeDept where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleDataScopeDept where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbIamRoleDataScopeDept where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleDataScopeDept whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbIamRoleDataScopeDept whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
