/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbJobLogRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 定时任务日志（追加表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbJobLog extends TableImpl<MbJobLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_job_log</code>
     */
    public static final MbJobLog MB_JOB_LOG = new MbJobLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbJobLogRecord> getRecordType() {
        return MbJobLogRecord.class;
    }

    /**
     * The column <code>public.mb_job_log.id</code>.
     */
    public final TableField<MbJobLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_job_log.job_name</code>.
     */
    public final TableField<MbJobLogRecord, String> JOB_NAME = createField(DSL.name("job_name"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_job_log.status</code>.
     */
    public final TableField<MbJobLogRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.mb_job_log.start_time</code>.
     */
    public final TableField<MbJobLogRecord, OffsetDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.mb_job_log.end_time</code>.
     */
    public final TableField<MbJobLogRecord, OffsetDateTime> END_TIME = createField(DSL.name("end_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.mb_job_log.duration_ms</code>.
     */
    public final TableField<MbJobLogRecord, Long> DURATION_MS = createField(DSL.name("duration_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_job_log.error_message</code>.
     */
    public final TableField<MbJobLogRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_job_log.created_at</code>.
     */
    public final TableField<MbJobLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbJobLog(Name alias, Table<MbJobLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbJobLog(Name alias, Table<MbJobLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("定时任务日志（追加表）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_job_log</code> table reference
     */
    public MbJobLog(String alias) {
        this(DSL.name(alias), MB_JOB_LOG);
    }

    /**
     * Create an aliased <code>public.mb_job_log</code> table reference
     */
    public MbJobLog(Name alias) {
        this(alias, MB_JOB_LOG);
    }

    /**
     * Create a <code>public.mb_job_log</code> table reference
     */
    public MbJobLog() {
        this(DSL.name("mb_job_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_JOB_LOG_NAME);
    }

    @Override
    public UniqueKey<MbJobLogRecord> getPrimaryKey() {
        return Keys.MB_JOB_LOG_PKEY;
    }

    @Override
    public MbJobLog as(String alias) {
        return new MbJobLog(DSL.name(alias), this);
    }

    @Override
    public MbJobLog as(Name alias) {
        return new MbJobLog(alias, this);
    }

    @Override
    public MbJobLog as(Table<?> alias) {
        return new MbJobLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbJobLog rename(String name) {
        return new MbJobLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbJobLog rename(Name name) {
        return new MbJobLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbJobLog rename(Table<?> name) {
        return new MbJobLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbJobLog where(Condition condition) {
        return new MbJobLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbJobLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbJobLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbJobLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbJobLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbJobLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbJobLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbJobLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbJobLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbJobLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
