/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamUser.MbIamUserPath;
import com.metabuild.schema.tables.records.MbLogOperationRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 操作日志（追加表，不注册 DataScope）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbLogOperation extends TableImpl<MbLogOperationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_log_operation</code>
     */
    public static final MbLogOperation MB_LOG_OPERATION = new MbLogOperation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbLogOperationRecord> getRecordType() {
        return MbLogOperationRecord.class;
    }

    /**
     * The column <code>public.mb_log_operation.id</code>.
     */
    public final TableField<MbLogOperationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_log_operation.tenant_id</code>.
     */
    public final TableField<MbLogOperationRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_log_operation.user_id</code>.
     */
    public final TableField<MbLogOperationRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_log_operation.username</code>.
     */
    public final TableField<MbLogOperationRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_log_operation.module</code>.
     */
    public final TableField<MbLogOperationRecord, String> MODULE = createField(DSL.name("module"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_log_operation.operation</code>.
     */
    public final TableField<MbLogOperationRecord, String> OPERATION = createField(DSL.name("operation"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_log_operation.method</code>.
     */
    public final TableField<MbLogOperationRecord, String> METHOD = createField(DSL.name("method"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_log_operation.request_url</code>.
     */
    public final TableField<MbLogOperationRecord, String> REQUEST_URL = createField(DSL.name("request_url"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_log_operation.request_params</code>.
     */
    public final TableField<MbLogOperationRecord, String> REQUEST_PARAMS = createField(DSL.name("request_params"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_log_operation.response_result</code>.
     */
    public final TableField<MbLogOperationRecord, String> RESPONSE_RESULT = createField(DSL.name("response_result"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_log_operation.ip</code>.
     */
    public final TableField<MbLogOperationRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.mb_log_operation.user_agent</code>.
     */
    public final TableField<MbLogOperationRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_log_operation.duration_ms</code>.
     */
    public final TableField<MbLogOperationRecord, Long> DURATION_MS = createField(DSL.name("duration_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_log_operation.success</code>.
     */
    public final TableField<MbLogOperationRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_log_operation.error_message</code>.
     */
    public final TableField<MbLogOperationRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_log_operation.created_at</code>.
     */
    public final TableField<MbLogOperationRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbLogOperation(Name alias, Table<MbLogOperationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbLogOperation(Name alias, Table<MbLogOperationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("操作日志（追加表，不注册 DataScope）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_log_operation</code> table reference
     */
    public MbLogOperation(String alias) {
        this(DSL.name(alias), MB_LOG_OPERATION);
    }

    /**
     * Create an aliased <code>public.mb_log_operation</code> table reference
     */
    public MbLogOperation(Name alias) {
        this(alias, MB_LOG_OPERATION);
    }

    /**
     * Create a <code>public.mb_log_operation</code> table reference
     */
    public MbLogOperation() {
        this(DSL.name("mb_log_operation"), null);
    }

    public <O extends Record> MbLogOperation(Table<O> path, ForeignKey<O, MbLogOperationRecord> childPath, InverseForeignKey<O, MbLogOperationRecord> parentPath) {
        super(path, childPath, parentPath, MB_LOG_OPERATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbLogOperationPath extends MbLogOperation implements Path<MbLogOperationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbLogOperationPath(Table<O> path, ForeignKey<O, MbLogOperationRecord> childPath, InverseForeignKey<O, MbLogOperationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbLogOperationPath(Name alias, Table<MbLogOperationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbLogOperationPath as(String alias) {
            return new MbLogOperationPath(DSL.name(alias), this);
        }

        @Override
        public MbLogOperationPath as(Name alias) {
            return new MbLogOperationPath(alias, this);
        }

        @Override
        public MbLogOperationPath as(Table<?> alias) {
            return new MbLogOperationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_LOG_OPERATION_MODULE, Indexes.IDX_LOG_OPERATION_TIME, Indexes.IDX_LOG_OPERATION_USER);
    }

    @Override
    public UniqueKey<MbLogOperationRecord> getPrimaryKey() {
        return Keys.MB_OPERATION_LOG_PKEY;
    }

    @Override
    public List<ForeignKey<MbLogOperationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_LOG_OPERATION__FK_LOG_OPERATION_USER);
    }

    private transient MbIamUserPath _mbIamUser;

    /**
     * Get the implicit join path to the <code>public.mb_iam_user</code> table.
     */
    public MbIamUserPath mbIamUser() {
        if (_mbIamUser == null)
            _mbIamUser = new MbIamUserPath(this, Keys.MB_LOG_OPERATION__FK_LOG_OPERATION_USER, null);

        return _mbIamUser;
    }

    @Override
    public MbLogOperation as(String alias) {
        return new MbLogOperation(DSL.name(alias), this);
    }

    @Override
    public MbLogOperation as(Name alias) {
        return new MbLogOperation(alias, this);
    }

    @Override
    public MbLogOperation as(Table<?> alias) {
        return new MbLogOperation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbLogOperation rename(String name) {
        return new MbLogOperation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbLogOperation rename(Name name) {
        return new MbLogOperation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbLogOperation rename(Table<?> name) {
        return new MbLogOperation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLogOperation where(Condition condition) {
        return new MbLogOperation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLogOperation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLogOperation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLogOperation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLogOperation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLogOperation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLogOperation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbLogOperation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLogOperation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbLogOperation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
