/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbNotificationDeliveryLogRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 通知投递日志（按渠道维度，区别于按收件人维度的 mb_notification_log）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationDeliveryLog extends TableImpl<MbNotificationDeliveryLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.mb_notification_delivery_log</code>
     */
    public static final MbNotificationDeliveryLog MB_NOTIFICATION_DELIVERY_LOG = new MbNotificationDeliveryLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbNotificationDeliveryLogRecord> getRecordType() {
        return MbNotificationDeliveryLogRecord.class;
    }

    /**
     * The column <code>public.mb_notification_delivery_log.id</code>.
     */
    public final TableField<MbNotificationDeliveryLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_notification_delivery_log.tenant_id</code>.
     */
    public final TableField<MbNotificationDeliveryLogRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_notification_delivery_log.business_id</code>.
     * 业务来源 ID（notice.id / order.id / approval.id），由 business_type 区分
     */
    public final TableField<MbNotificationDeliveryLogRecord, Long> BUSINESS_ID = createField(DSL.name("business_id"), SQLDataType.BIGINT, this, "业务来源 ID（notice.id / order.id / approval.id），由 business_type 区分");

    /**
     * The column <code>public.mb_notification_delivery_log.channel</code>.
     * 渠道：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> CHANNEL = createField(DSL.name("channel"), SQLDataType.VARCHAR(32).nullable(false), this, "渠道：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI");

    /**
     * The column
     * <code>public.mb_notification_delivery_log.recipient_count</code>.
     * 本次投递的收件人数量
     */
    public final TableField<MbNotificationDeliveryLogRecord, Integer> RECIPIENT_COUNT = createField(DSL.name("recipient_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "本次投递的收件人数量");

    /**
     * The column <code>public.mb_notification_delivery_log.status</code>.
     * 状态：SUCCESS/TIMEOUT/FAILED
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false), this, "状态：SUCCESS/TIMEOUT/FAILED");

    /**
     * The column <code>public.mb_notification_delivery_log.duration_ms</code>.
     * 耗时（毫秒，BIGINT）
     */
    public final TableField<MbNotificationDeliveryLogRecord, Long> DURATION_MS = createField(DSL.name("duration_ms"), SQLDataType.BIGINT.nullable(false), this, "耗时（毫秒，BIGINT）");

    /**
     * The column <code>public.mb_notification_delivery_log.error_code</code>.
     * 失败错误码
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> ERROR_CODE = createField(DSL.name("error_code"), SQLDataType.VARCHAR(64), this, "失败错误码");

    /**
     * The column
     * <code>public.mb_notification_delivery_log.error_message</code>. 失败信息（最多
     * 500 字符）
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.VARCHAR(500), this, "失败信息（最多 500 字符）");

    /**
     * The column <code>public.mb_notification_delivery_log.created_at</code>.
     */
    public final TableField<MbNotificationDeliveryLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column
     * <code>public.mb_notification_delivery_log.business_type</code>.
     * 业务大类：NOTICE / ORDER / APPROVAL 等
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> BUSINESS_TYPE = createField(DSL.name("business_type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'UNKNOWN'::character varying"), SQLDataType.VARCHAR)), this, "业务大类：NOTICE / ORDER / APPROVAL 等");

    /**
     * The column <code>public.mb_notification_delivery_log.event_type</code>.
     * 业务事件：NOTICE_PUBLISHED / ORDER_SHIPPED 等
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.VARCHAR(64), this, "业务事件：NOTICE_PUBLISHED / ORDER_SHIPPED 等");

    /**
     * The column <code>public.mb_notification_delivery_log.message_type</code>.
     * 消息格式：TEXT / HTML / TEMPLATE / CARD 等（区别于 channel 投递渠道）
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> MESSAGE_TYPE = createField(DSL.name("message_type"), SQLDataType.VARCHAR(32), this, "消息格式：TEXT / HTML / TEMPLATE / CARD 等（区别于 channel 投递渠道）");

    /**
     * The column <code>public.mb_notification_delivery_log.trace_id</code>. MDC
     * 链路追踪 ID，关联 ELK / OpenTelemetry 日志
     */
    public final TableField<MbNotificationDeliveryLogRecord, String> TRACE_ID = createField(DSL.name("trace_id"), SQLDataType.VARCHAR(64), this, "MDC 链路追踪 ID，关联 ELK / OpenTelemetry 日志");

    private MbNotificationDeliveryLog(Name alias, Table<MbNotificationDeliveryLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbNotificationDeliveryLog(Name alias, Table<MbNotificationDeliveryLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("通知投递日志（按渠道维度，区别于按收件人维度的 mb_notification_log）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_notification_delivery_log</code> table
     * reference
     */
    public MbNotificationDeliveryLog(String alias) {
        this(DSL.name(alias), MB_NOTIFICATION_DELIVERY_LOG);
    }

    /**
     * Create an aliased <code>public.mb_notification_delivery_log</code> table
     * reference
     */
    public MbNotificationDeliveryLog(Name alias) {
        this(alias, MB_NOTIFICATION_DELIVERY_LOG);
    }

    /**
     * Create a <code>public.mb_notification_delivery_log</code> table reference
     */
    public MbNotificationDeliveryLog() {
        this(DSL.name("mb_notification_delivery_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTIF_DELIVERY_LOG_BUSINESS_CHANNEL, Indexes.IDX_NOTIF_DELIVERY_LOG_CREATED_AT, Indexes.IDX_NOTIF_DELIVERY_LOG_STATUS);
    }

    @Override
    public UniqueKey<MbNotificationDeliveryLogRecord> getPrimaryKey() {
        return Keys.MB_NOTIFICATION_DELIVERY_LOG_PKEY;
    }

    @Override
    public MbNotificationDeliveryLog as(String alias) {
        return new MbNotificationDeliveryLog(DSL.name(alias), this);
    }

    @Override
    public MbNotificationDeliveryLog as(Name alias) {
        return new MbNotificationDeliveryLog(alias, this);
    }

    @Override
    public MbNotificationDeliveryLog as(Table<?> alias) {
        return new MbNotificationDeliveryLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotificationDeliveryLog rename(String name) {
        return new MbNotificationDeliveryLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotificationDeliveryLog rename(Name name) {
        return new MbNotificationDeliveryLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotificationDeliveryLog rename(Table<?> name) {
        return new MbNotificationDeliveryLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationDeliveryLog where(Condition condition) {
        return new MbNotificationDeliveryLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationDeliveryLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationDeliveryLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationDeliveryLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationDeliveryLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationDeliveryLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationDeliveryLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationDeliveryLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationDeliveryLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationDeliveryLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
