/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbNotificationReadRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 通知已读记录（追加表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationRead extends TableImpl<MbNotificationReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_notification_read</code>
     */
    public static final MbNotificationRead MB_NOTIFICATION_READ = new MbNotificationRead();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbNotificationReadRecord> getRecordType() {
        return MbNotificationReadRecord.class;
    }

    /**
     * The column <code>public.mb_notification_read.notification_id</code>.
     */
    public final TableField<MbNotificationReadRecord, Long> NOTIFICATION_ID = createField(DSL.name("notification_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_notification_read.user_id</code>.
     */
    public final TableField<MbNotificationReadRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_notification_read.read_at</code>.
     */
    public final TableField<MbNotificationReadRecord, OffsetDateTime> READ_AT = createField(DSL.name("read_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbNotificationRead(Name alias, Table<MbNotificationReadRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbNotificationRead(Name alias, Table<MbNotificationReadRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("通知已读记录（追加表）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_notification_read</code> table
     * reference
     */
    public MbNotificationRead(String alias) {
        this(DSL.name(alias), MB_NOTIFICATION_READ);
    }

    /**
     * Create an aliased <code>public.mb_notification_read</code> table
     * reference
     */
    public MbNotificationRead(Name alias) {
        this(alias, MB_NOTIFICATION_READ);
    }

    /**
     * Create a <code>public.mb_notification_read</code> table reference
     */
    public MbNotificationRead() {
        this(DSL.name("mb_notification_read"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MbNotificationReadRecord> getPrimaryKey() {
        return Keys.MB_NOTIFICATION_READ_PKEY;
    }

    @Override
    public MbNotificationRead as(String alias) {
        return new MbNotificationRead(DSL.name(alias), this);
    }

    @Override
    public MbNotificationRead as(Name alias) {
        return new MbNotificationRead(alias, this);
    }

    @Override
    public MbNotificationRead as(Table<?> alias) {
        return new MbNotificationRead(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotificationRead rename(String name) {
        return new MbNotificationRead(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotificationRead rename(Name name) {
        return new MbNotificationRead(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotificationRead rename(Table<?> name) {
        return new MbNotificationRead(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationRead where(Condition condition) {
        return new MbNotificationRead(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationRead where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationRead where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationRead where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationRead where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationRead where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationRead where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotificationRead where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationRead whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotificationRead whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
