/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.MbIamUser.MbIamUserPath;
import com.metabuild.schema.tables.MbNotificationRead.MbNotificationReadPath;
import com.metabuild.schema.tables.records.MbNotificationRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 通知公告表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotification extends TableImpl<MbNotificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_notification</code>
     */
    public static final MbNotification MB_NOTIFICATION = new MbNotification();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbNotificationRecord> getRecordType() {
        return MbNotificationRecord.class;
    }

    /**
     * The column <code>public.mb_notification.id</code>.
     */
    public final TableField<MbNotificationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_notification.tenant_id</code>.
     */
    public final TableField<MbNotificationRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_notification.title</code>.
     */
    public final TableField<MbNotificationRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_notification.content</code>.
     */
    public final TableField<MbNotificationRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_notification.type</code>.
     */
    public final TableField<MbNotificationRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'SYSTEM'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.mb_notification.sender_id</code>.
     */
    public final TableField<MbNotificationRecord, Long> SENDER_ID = createField(DSL.name("sender_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_notification.status</code>.
     */
    public final TableField<MbNotificationRecord, Short> STATUS = createField(DSL.name("status"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.mb_notification.owner_dept_id</code>.
     */
    public final TableField<MbNotificationRecord, Long> OWNER_DEPT_ID = createField(DSL.name("owner_dept_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_notification.version</code>.
     */
    public final TableField<MbNotificationRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.mb_notification.created_by</code>.
     */
    public final TableField<MbNotificationRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_notification.created_at</code>.
     */
    public final TableField<MbNotificationRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.mb_notification.updated_by</code>.
     */
    public final TableField<MbNotificationRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_notification.updated_at</code>.
     */
    public final TableField<MbNotificationRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbNotification(Name alias, Table<MbNotificationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbNotification(Name alias, Table<MbNotificationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("通知公告表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_notification</code> table reference
     */
    public MbNotification(String alias) {
        this(DSL.name(alias), MB_NOTIFICATION);
    }

    /**
     * Create an aliased <code>public.mb_notification</code> table reference
     */
    public MbNotification(Name alias) {
        this(alias, MB_NOTIFICATION);
    }

    /**
     * Create a <code>public.mb_notification</code> table reference
     */
    public MbNotification() {
        this(DSL.name("mb_notification"), null);
    }

    public <O extends Record> MbNotification(Table<O> path, ForeignKey<O, MbNotificationRecord> childPath, InverseForeignKey<O, MbNotificationRecord> parentPath) {
        super(path, childPath, parentPath, MB_NOTIFICATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MbNotificationPath extends MbNotification implements Path<MbNotificationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MbNotificationPath(Table<O> path, ForeignKey<O, MbNotificationRecord> childPath, InverseForeignKey<O, MbNotificationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MbNotificationPath(Name alias, Table<MbNotificationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MbNotificationPath as(String alias) {
            return new MbNotificationPath(DSL.name(alias), this);
        }

        @Override
        public MbNotificationPath as(Name alias) {
            return new MbNotificationPath(alias, this);
        }

        @Override
        public MbNotificationPath as(Table<?> alias) {
            return new MbNotificationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_NOTIFICATION_STATUS, Indexes.IDX_NOTIFICATION_TIME);
    }

    @Override
    public UniqueKey<MbNotificationRecord> getPrimaryKey() {
        return Keys.MB_NOTIFICATION_PKEY;
    }

    @Override
    public List<ForeignKey<MbNotificationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MB_NOTIFICATION__FK_NOTIFICATION_SENDER);
    }

    private transient MbIamUserPath _mbIamUser;

    /**
     * Get the implicit join path to the <code>public.mb_iam_user</code> table.
     */
    public MbIamUserPath mbIamUser() {
        if (_mbIamUser == null)
            _mbIamUser = new MbIamUserPath(this, Keys.MB_NOTIFICATION__FK_NOTIFICATION_SENDER, null);

        return _mbIamUser;
    }

    private transient MbNotificationReadPath _mbNotificationRead;

    /**
     * Get the implicit to-many join path to the
     * <code>public.mb_notification_read</code> table
     */
    public MbNotificationReadPath mbNotificationRead() {
        if (_mbNotificationRead == null)
            _mbNotificationRead = new MbNotificationReadPath(this, null, Keys.MB_NOTIFICATION_READ__FK_NOTIFICATION_READ_NOTIFICATION.getInverseKey());

        return _mbNotificationRead;
    }

    @Override
    public List<Check<MbNotificationRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_notification_status"), "((status = ANY (ARRAY[0, 1, 2])))", true),
            Internal.createCheck(this, DSL.name("chk_notification_type"), "(((type)::text = ANY ((ARRAY['SYSTEM'::character varying, 'BUSINESS'::character varying, 'APPROVAL'::character varying])::text[])))", true)
        );
    }

    @Override
    public MbNotification as(String alias) {
        return new MbNotification(DSL.name(alias), this);
    }

    @Override
    public MbNotification as(Name alias) {
        return new MbNotification(alias, this);
    }

    @Override
    public MbNotification as(Table<?> alias) {
        return new MbNotification(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotification rename(String name) {
        return new MbNotification(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotification rename(Name name) {
        return new MbNotification(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbNotification rename(Table<?> name) {
        return new MbNotification(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotification where(Condition condition) {
        return new MbNotification(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotification where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotification where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotification where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotification where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotification where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotification where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbNotification where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotification whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbNotification whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
