/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbOperationLogRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 操作日志（追加表，不注册 DataScope）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbOperationLog extends TableImpl<MbOperationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_operation_log</code>
     */
    public static final MbOperationLog MB_OPERATION_LOG = new MbOperationLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbOperationLogRecord> getRecordType() {
        return MbOperationLogRecord.class;
    }

    /**
     * The column <code>public.mb_operation_log.id</code>.
     */
    public final TableField<MbOperationLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.tenant_id</code>.
     */
    public final TableField<MbOperationLogRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.mb_operation_log.user_id</code>.
     */
    public final TableField<MbOperationLogRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.username</code>.
     */
    public final TableField<MbOperationLogRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.module</code>.
     */
    public final TableField<MbOperationLogRecord, String> MODULE = createField(DSL.name("module"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.operation</code>.
     */
    public final TableField<MbOperationLogRecord, String> OPERATION = createField(DSL.name("operation"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.method</code>.
     */
    public final TableField<MbOperationLogRecord, String> METHOD = createField(DSL.name("method"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.mb_operation_log.request_url</code>.
     */
    public final TableField<MbOperationLogRecord, String> REQUEST_URL = createField(DSL.name("request_url"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_operation_log.request_params</code>.
     */
    public final TableField<MbOperationLogRecord, String> REQUEST_PARAMS = createField(DSL.name("request_params"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_operation_log.response_result</code>.
     */
    public final TableField<MbOperationLogRecord, String> RESPONSE_RESULT = createField(DSL.name("response_result"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_operation_log.ip</code>.
     */
    public final TableField<MbOperationLogRecord, String> IP = createField(DSL.name("ip"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.mb_operation_log.user_agent</code>.
     */
    public final TableField<MbOperationLogRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.mb_operation_log.duration_ms</code>.
     */
    public final TableField<MbOperationLogRecord, Long> DURATION_MS = createField(DSL.name("duration_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.mb_operation_log.success</code>.
     */
    public final TableField<MbOperationLogRecord, Boolean> SUCCESS = createField(DSL.name("success"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.mb_operation_log.error_message</code>.
     */
    public final TableField<MbOperationLogRecord, String> ERROR_MESSAGE = createField(DSL.name("error_message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.mb_operation_log.created_at</code>.
     */
    public final TableField<MbOperationLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MbOperationLog(Name alias, Table<MbOperationLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbOperationLog(Name alias, Table<MbOperationLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("操作日志（追加表，不注册 DataScope）"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_operation_log</code> table reference
     */
    public MbOperationLog(String alias) {
        this(DSL.name(alias), MB_OPERATION_LOG);
    }

    /**
     * Create an aliased <code>public.mb_operation_log</code> table reference
     */
    public MbOperationLog(Name alias) {
        this(alias, MB_OPERATION_LOG);
    }

    /**
     * Create a <code>public.mb_operation_log</code> table reference
     */
    public MbOperationLog() {
        this(DSL.name("mb_operation_log"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OPLOG_MODULE, Indexes.IDX_OPLOG_TIME, Indexes.IDX_OPLOG_USER);
    }

    @Override
    public UniqueKey<MbOperationLogRecord> getPrimaryKey() {
        return Keys.MB_OPERATION_LOG_PKEY;
    }

    @Override
    public MbOperationLog as(String alias) {
        return new MbOperationLog(DSL.name(alias), this);
    }

    @Override
    public MbOperationLog as(Name alias) {
        return new MbOperationLog(alias, this);
    }

    @Override
    public MbOperationLog as(Table<?> alias) {
        return new MbOperationLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbOperationLog rename(String name) {
        return new MbOperationLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbOperationLog rename(Name name) {
        return new MbOperationLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbOperationLog rename(Table<?> name) {
        return new MbOperationLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Condition condition) {
        return new MbOperationLog(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbOperationLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbOperationLog whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
