/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables;


import com.metabuild.schema.Indexes;
import com.metabuild.schema.Keys;
import com.metabuild.schema.Public;
import com.metabuild.schema.tables.records.MbUserWechatBindingRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 微信绑定关系
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbUserWechatBinding extends TableImpl<MbUserWechatBindingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.mb_user_wechat_binding</code>
     */
    public static final MbUserWechatBinding MB_USER_WECHAT_BINDING = new MbUserWechatBinding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MbUserWechatBindingRecord> getRecordType() {
        return MbUserWechatBindingRecord.class;
    }

    /**
     * The column <code>public.mb_user_wechat_binding.id</code>.
     */
    public final TableField<MbUserWechatBindingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.mb_user_wechat_binding.tenant_id</code>. 租户 ID（v1
     * 默认 0）
     */
    public final TableField<MbUserWechatBindingRecord, Long> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "租户 ID（v1 默认 0）");

    /**
     * The column <code>public.mb_user_wechat_binding.user_id</code>. 系统用户 ID
     */
    public final TableField<MbUserWechatBindingRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "系统用户 ID");

    /**
     * The column <code>public.mb_user_wechat_binding.platform</code>.
     * 平台类型：MP=公众号 MINI=小程序
     */
    public final TableField<MbUserWechatBindingRecord, String> PLATFORM = createField(DSL.name("platform"), SQLDataType.VARCHAR(20).nullable(false), this, "平台类型：MP=公众号 MINI=小程序");

    /**
     * The column <code>public.mb_user_wechat_binding.app_id</code>. 微信应用 AppID
     */
    public final TableField<MbUserWechatBindingRecord, String> APP_ID = createField(DSL.name("app_id"), SQLDataType.VARCHAR(64).nullable(false), this, "微信应用 AppID");

    /**
     * The column <code>public.mb_user_wechat_binding.open_id</code>. 微信
     * OpenID（同一用户在不同应用有不同 OpenID）
     */
    public final TableField<MbUserWechatBindingRecord, String> OPEN_ID = createField(DSL.name("open_id"), SQLDataType.VARCHAR(64).nullable(false), this, "微信 OpenID（同一用户在不同应用有不同 OpenID）");

    /**
     * The column <code>public.mb_user_wechat_binding.union_id</code>.
     * UnionID（同一开放平台下多应用共享）
     */
    public final TableField<MbUserWechatBindingRecord, String> UNION_ID = createField(DSL.name("union_id"), SQLDataType.VARCHAR(64), this, "UnionID（同一开放平台下多应用共享）");

    /**
     * The column <code>public.mb_user_wechat_binding.nickname</code>. 微信昵称
     */
    public final TableField<MbUserWechatBindingRecord, String> NICKNAME = createField(DSL.name("nickname"), SQLDataType.VARCHAR(100), this, "微信昵称");

    /**
     * The column <code>public.mb_user_wechat_binding.avatar_url</code>. 微信头像
     * URL
     */
    public final TableField<MbUserWechatBindingRecord, String> AVATAR_URL = createField(DSL.name("avatar_url"), SQLDataType.VARCHAR(500), this, "微信头像 URL");

    /**
     * The column <code>public.mb_user_wechat_binding.bound_at</code>. 绑定时间
     */
    public final TableField<MbUserWechatBindingRecord, OffsetDateTime> BOUND_AT = createField(DSL.name("bound_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "绑定时间");

    private MbUserWechatBinding(Name alias, Table<MbUserWechatBindingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MbUserWechatBinding(Name alias, Table<MbUserWechatBindingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("微信绑定关系"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.mb_user_wechat_binding</code> table
     * reference
     */
    public MbUserWechatBinding(String alias) {
        this(DSL.name(alias), MB_USER_WECHAT_BINDING);
    }

    /**
     * Create an aliased <code>public.mb_user_wechat_binding</code> table
     * reference
     */
    public MbUserWechatBinding(Name alias) {
        this(alias, MB_USER_WECHAT_BINDING);
    }

    /**
     * Create a <code>public.mb_user_wechat_binding</code> table reference
     */
    public MbUserWechatBinding() {
        this(DSL.name("mb_user_wechat_binding"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_WECHAT_BINDING_OPENID, Indexes.IDX_WECHAT_BINDING_USER);
    }

    @Override
    public UniqueKey<MbUserWechatBindingRecord> getPrimaryKey() {
        return Keys.MB_USER_WECHAT_BINDING_PKEY;
    }

    @Override
    public List<UniqueKey<MbUserWechatBindingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MB_USER_WECHAT_BINDING_TENANT_ID_USER_ID_PLATFORM_APP_ID_KEY);
    }

    @Override
    public MbUserWechatBinding as(String alias) {
        return new MbUserWechatBinding(DSL.name(alias), this);
    }

    @Override
    public MbUserWechatBinding as(Name alias) {
        return new MbUserWechatBinding(alias, this);
    }

    @Override
    public MbUserWechatBinding as(Table<?> alias) {
        return new MbUserWechatBinding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserWechatBinding rename(String name) {
        return new MbUserWechatBinding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserWechatBinding rename(Name name) {
        return new MbUserWechatBinding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MbUserWechatBinding rename(Table<?> name) {
        return new MbUserWechatBinding(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserWechatBinding where(Condition condition) {
        return new MbUserWechatBinding(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserWechatBinding where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserWechatBinding where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserWechatBinding where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserWechatBinding where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserWechatBinding where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserWechatBinding where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MbUserWechatBinding where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserWechatBinding whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MbUserWechatBinding whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
