/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema;


import com.metabuild.schema.tables.MbConfig;
import com.metabuild.schema.tables.MbDictData;
import com.metabuild.schema.tables.MbDictType;
import com.metabuild.schema.tables.MbFileMetadata;
import com.metabuild.schema.tables.MbIamDept;
import com.metabuild.schema.tables.MbIamLoginLog;
import com.metabuild.schema.tables.MbIamMenu;
import com.metabuild.schema.tables.MbIamPasswordHistory;
import com.metabuild.schema.tables.MbIamRole;
import com.metabuild.schema.tables.MbIamRoleDataScopeDept;
import com.metabuild.schema.tables.MbIamRoleMenu;
import com.metabuild.schema.tables.MbIamRouteTree;
import com.metabuild.schema.tables.MbIamUser;
import com.metabuild.schema.tables.MbIamUserRole;
import com.metabuild.schema.tables.MbJobLog;
import com.metabuild.schema.tables.MbNotification;
import com.metabuild.schema.tables.MbNotificationRead;
import com.metabuild.schema.tables.MbOperationLog;
import com.metabuild.schema.tables.records.MbConfigRecord;
import com.metabuild.schema.tables.records.MbDictDataRecord;
import com.metabuild.schema.tables.records.MbDictTypeRecord;
import com.metabuild.schema.tables.records.MbFileMetadataRecord;
import com.metabuild.schema.tables.records.MbIamDeptRecord;
import com.metabuild.schema.tables.records.MbIamLoginLogRecord;
import com.metabuild.schema.tables.records.MbIamMenuRecord;
import com.metabuild.schema.tables.records.MbIamPasswordHistoryRecord;
import com.metabuild.schema.tables.records.MbIamRoleDataScopeDeptRecord;
import com.metabuild.schema.tables.records.MbIamRoleMenuRecord;
import com.metabuild.schema.tables.records.MbIamRoleRecord;
import com.metabuild.schema.tables.records.MbIamRouteTreeRecord;
import com.metabuild.schema.tables.records.MbIamUserRecord;
import com.metabuild.schema.tables.records.MbIamUserRoleRecord;
import com.metabuild.schema.tables.records.MbJobLogRecord;
import com.metabuild.schema.tables.records.MbNotificationReadRecord;
import com.metabuild.schema.tables.records.MbNotificationRecord;
import com.metabuild.schema.tables.records.MbOperationLogRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MbConfigRecord> MB_CONFIG_PKEY = Internal.createUniqueKey(MbConfig.MB_CONFIG, DSL.name("mb_config_pkey"), new TableField[] { MbConfig.MB_CONFIG.ID }, true);
    public static final UniqueKey<MbDictDataRecord> MB_DICT_DATA_PKEY = Internal.createUniqueKey(MbDictData.MB_DICT_DATA, DSL.name("mb_dict_data_pkey"), new TableField[] { MbDictData.MB_DICT_DATA.ID }, true);
    public static final UniqueKey<MbDictTypeRecord> MB_DICT_TYPE_PKEY = Internal.createUniqueKey(MbDictType.MB_DICT_TYPE, DSL.name("mb_dict_type_pkey"), new TableField[] { MbDictType.MB_DICT_TYPE.ID }, true);
    public static final UniqueKey<MbFileMetadataRecord> MB_FILE_METADATA_PKEY = Internal.createUniqueKey(MbFileMetadata.MB_FILE_METADATA, DSL.name("mb_file_metadata_pkey"), new TableField[] { MbFileMetadata.MB_FILE_METADATA.ID }, true);
    public static final UniqueKey<MbIamDeptRecord> MB_IAM_DEPT_PKEY = Internal.createUniqueKey(MbIamDept.MB_IAM_DEPT, DSL.name("mb_iam_dept_pkey"), new TableField[] { MbIamDept.MB_IAM_DEPT.ID }, true);
    public static final UniqueKey<MbIamLoginLogRecord> MB_IAM_LOGIN_LOG_PKEY = Internal.createUniqueKey(MbIamLoginLog.MB_IAM_LOGIN_LOG, DSL.name("mb_iam_login_log_pkey"), new TableField[] { MbIamLoginLog.MB_IAM_LOGIN_LOG.ID }, true);
    public static final UniqueKey<MbIamMenuRecord> MB_IAM_MENU_PKEY = Internal.createUniqueKey(MbIamMenu.MB_IAM_MENU, DSL.name("mb_iam_menu_pkey"), new TableField[] { MbIamMenu.MB_IAM_MENU.ID }, true);
    public static final UniqueKey<MbIamPasswordHistoryRecord> MB_IAM_PASSWORD_HISTORY_PKEY = Internal.createUniqueKey(MbIamPasswordHistory.MB_IAM_PASSWORD_HISTORY, DSL.name("mb_iam_password_history_pkey"), new TableField[] { MbIamPasswordHistory.MB_IAM_PASSWORD_HISTORY.ID }, true);
    public static final UniqueKey<MbIamRoleRecord> MB_IAM_ROLE_PKEY = Internal.createUniqueKey(MbIamRole.MB_IAM_ROLE, DSL.name("mb_iam_role_pkey"), new TableField[] { MbIamRole.MB_IAM_ROLE.ID }, true);
    public static final UniqueKey<MbIamRoleDataScopeDeptRecord> MB_IAM_ROLE_DATA_SCOPE_DEPT_PKEY = Internal.createUniqueKey(MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT, DSL.name("mb_iam_role_data_scope_dept_pkey"), new TableField[] { MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT.ROLE_ID, MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT.DEPT_ID }, true);
    public static final UniqueKey<MbIamRoleMenuRecord> MB_IAM_ROLE_MENU_PKEY = Internal.createUniqueKey(MbIamRoleMenu.MB_IAM_ROLE_MENU, DSL.name("mb_iam_role_menu_pkey"), new TableField[] { MbIamRoleMenu.MB_IAM_ROLE_MENU.ROLE_ID, MbIamRoleMenu.MB_IAM_ROLE_MENU.MENU_ID }, true);
    public static final UniqueKey<MbIamRouteTreeRecord> MB_IAM_ROUTE_TREE_PKEY = Internal.createUniqueKey(MbIamRouteTree.MB_IAM_ROUTE_TREE, DSL.name("mb_iam_route_tree_pkey"), new TableField[] { MbIamRouteTree.MB_IAM_ROUTE_TREE.ID }, true);
    public static final UniqueKey<MbIamUserRecord> MB_IAM_USER_PKEY = Internal.createUniqueKey(MbIamUser.MB_IAM_USER, DSL.name("mb_iam_user_pkey"), new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final UniqueKey<MbIamUserRoleRecord> MB_IAM_USER_ROLE_PKEY = Internal.createUniqueKey(MbIamUserRole.MB_IAM_USER_ROLE, DSL.name("mb_iam_user_role_pkey"), new TableField[] { MbIamUserRole.MB_IAM_USER_ROLE.USER_ID, MbIamUserRole.MB_IAM_USER_ROLE.ROLE_ID }, true);
    public static final UniqueKey<MbJobLogRecord> MB_JOB_LOG_PKEY = Internal.createUniqueKey(MbJobLog.MB_JOB_LOG, DSL.name("mb_job_log_pkey"), new TableField[] { MbJobLog.MB_JOB_LOG.ID }, true);
    public static final UniqueKey<MbNotificationRecord> MB_NOTIFICATION_PKEY = Internal.createUniqueKey(MbNotification.MB_NOTIFICATION, DSL.name("mb_notification_pkey"), new TableField[] { MbNotification.MB_NOTIFICATION.ID }, true);
    public static final UniqueKey<MbNotificationReadRecord> MB_NOTIFICATION_READ_PKEY = Internal.createUniqueKey(MbNotificationRead.MB_NOTIFICATION_READ, DSL.name("mb_notification_read_pkey"), new TableField[] { MbNotificationRead.MB_NOTIFICATION_READ.NOTIFICATION_ID, MbNotificationRead.MB_NOTIFICATION_READ.USER_ID }, true);
    public static final UniqueKey<MbOperationLogRecord> MB_OPERATION_LOG_PKEY = Internal.createUniqueKey(MbOperationLog.MB_OPERATION_LOG, DSL.name("mb_operation_log_pkey"), new TableField[] { MbOperationLog.MB_OPERATION_LOG.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MbDictDataRecord, MbDictTypeRecord> MB_DICT_DATA__FK_DICT_DATA_DICT_TYPE = Internal.createForeignKey(MbDictData.MB_DICT_DATA, DSL.name("fk_dict_data_dict_type"), new TableField[] { MbDictData.MB_DICT_DATA.DICT_TYPE_ID }, Keys.MB_DICT_TYPE_PKEY, new TableField[] { MbDictType.MB_DICT_TYPE.ID }, true);
    public static final ForeignKey<MbFileMetadataRecord, MbIamUserRecord> MB_FILE_METADATA__FK_FILE_METADATA_UPLOADER = Internal.createForeignKey(MbFileMetadata.MB_FILE_METADATA, DSL.name("fk_file_metadata_uploader"), new TableField[] { MbFileMetadata.MB_FILE_METADATA.UPLOADER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbIamDeptRecord, MbIamUserRecord> MB_IAM_DEPT__FK_IAM_DEPT_LEADER = Internal.createForeignKey(MbIamDept.MB_IAM_DEPT, DSL.name("fk_iam_dept_leader"), new TableField[] { MbIamDept.MB_IAM_DEPT.LEADER_USER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbIamDeptRecord, MbIamDeptRecord> MB_IAM_DEPT__FK_IAM_DEPT_PARENT = Internal.createForeignKey(MbIamDept.MB_IAM_DEPT, DSL.name("fk_iam_dept_parent"), new TableField[] { MbIamDept.MB_IAM_DEPT.PARENT_ID }, Keys.MB_IAM_DEPT_PKEY, new TableField[] { MbIamDept.MB_IAM_DEPT.ID }, true);
    public static final ForeignKey<MbIamLoginLogRecord, MbIamUserRecord> MB_IAM_LOGIN_LOG__FK_IAM_LOGIN_LOG_USER = Internal.createForeignKey(MbIamLoginLog.MB_IAM_LOGIN_LOG, DSL.name("fk_iam_login_log_user"), new TableField[] { MbIamLoginLog.MB_IAM_LOGIN_LOG.USER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbIamMenuRecord, MbIamMenuRecord> MB_IAM_MENU__FK_IAM_MENU_PARENT = Internal.createForeignKey(MbIamMenu.MB_IAM_MENU, DSL.name("fk_iam_menu_parent"), new TableField[] { MbIamMenu.MB_IAM_MENU.PARENT_ID }, Keys.MB_IAM_MENU_PKEY, new TableField[] { MbIamMenu.MB_IAM_MENU.ID }, true);
    public static final ForeignKey<MbIamPasswordHistoryRecord, MbIamUserRecord> MB_IAM_PASSWORD_HISTORY__FK_IAM_PASSWORD_HISTORY_USER = Internal.createForeignKey(MbIamPasswordHistory.MB_IAM_PASSWORD_HISTORY, DSL.name("fk_iam_password_history_user"), new TableField[] { MbIamPasswordHistory.MB_IAM_PASSWORD_HISTORY.USER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbIamRoleDataScopeDeptRecord, MbIamDeptRecord> MB_IAM_ROLE_DATA_SCOPE_DEPT__FK_IAM_ROLE_DSD_DEPT = Internal.createForeignKey(MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT, DSL.name("fk_iam_role_dsd_dept"), new TableField[] { MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT.DEPT_ID }, Keys.MB_IAM_DEPT_PKEY, new TableField[] { MbIamDept.MB_IAM_DEPT.ID }, true);
    public static final ForeignKey<MbIamRoleDataScopeDeptRecord, MbIamRoleRecord> MB_IAM_ROLE_DATA_SCOPE_DEPT__FK_IAM_ROLE_DSD_ROLE = Internal.createForeignKey(MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT, DSL.name("fk_iam_role_dsd_role"), new TableField[] { MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT.ROLE_ID }, Keys.MB_IAM_ROLE_PKEY, new TableField[] { MbIamRole.MB_IAM_ROLE.ID }, true);
    public static final ForeignKey<MbIamRoleMenuRecord, MbIamMenuRecord> MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_MENU = Internal.createForeignKey(MbIamRoleMenu.MB_IAM_ROLE_MENU, DSL.name("fk_iam_role_menu_menu"), new TableField[] { MbIamRoleMenu.MB_IAM_ROLE_MENU.MENU_ID }, Keys.MB_IAM_MENU_PKEY, new TableField[] { MbIamMenu.MB_IAM_MENU.ID }, true);
    public static final ForeignKey<MbIamRoleMenuRecord, MbIamRoleRecord> MB_IAM_ROLE_MENU__FK_IAM_ROLE_MENU_ROLE = Internal.createForeignKey(MbIamRoleMenu.MB_IAM_ROLE_MENU, DSL.name("fk_iam_role_menu_role"), new TableField[] { MbIamRoleMenu.MB_IAM_ROLE_MENU.ROLE_ID }, Keys.MB_IAM_ROLE_PKEY, new TableField[] { MbIamRole.MB_IAM_ROLE.ID }, true);
    public static final ForeignKey<MbIamRouteTreeRecord, MbIamRouteTreeRecord> MB_IAM_ROUTE_TREE__FK_IAM_ROUTE_TREE_PARENT = Internal.createForeignKey(MbIamRouteTree.MB_IAM_ROUTE_TREE, DSL.name("fk_iam_route_tree_parent"), new TableField[] { MbIamRouteTree.MB_IAM_ROUTE_TREE.PARENT_ID }, Keys.MB_IAM_ROUTE_TREE_PKEY, new TableField[] { MbIamRouteTree.MB_IAM_ROUTE_TREE.ID }, true);
    public static final ForeignKey<MbIamUserRecord, MbIamDeptRecord> MB_IAM_USER__FK_IAM_USER_DEPT = Internal.createForeignKey(MbIamUser.MB_IAM_USER, DSL.name("fk_iam_user_dept"), new TableField[] { MbIamUser.MB_IAM_USER.DEPT_ID }, Keys.MB_IAM_DEPT_PKEY, new TableField[] { MbIamDept.MB_IAM_DEPT.ID }, true);
    public static final ForeignKey<MbIamUserRoleRecord, MbIamRoleRecord> MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_ROLE = Internal.createForeignKey(MbIamUserRole.MB_IAM_USER_ROLE, DSL.name("fk_iam_user_role_role"), new TableField[] { MbIamUserRole.MB_IAM_USER_ROLE.ROLE_ID }, Keys.MB_IAM_ROLE_PKEY, new TableField[] { MbIamRole.MB_IAM_ROLE.ID }, true);
    public static final ForeignKey<MbIamUserRoleRecord, MbIamUserRecord> MB_IAM_USER_ROLE__FK_IAM_USER_ROLE_USER = Internal.createForeignKey(MbIamUserRole.MB_IAM_USER_ROLE, DSL.name("fk_iam_user_role_user"), new TableField[] { MbIamUserRole.MB_IAM_USER_ROLE.USER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbNotificationRecord, MbIamUserRecord> MB_NOTIFICATION__FK_NOTIFICATION_SENDER = Internal.createForeignKey(MbNotification.MB_NOTIFICATION, DSL.name("fk_notification_sender"), new TableField[] { MbNotification.MB_NOTIFICATION.SENDER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbNotificationReadRecord, MbNotificationRecord> MB_NOTIFICATION_READ__FK_NOTIFICATION_READ_NOTIFICATION = Internal.createForeignKey(MbNotificationRead.MB_NOTIFICATION_READ, DSL.name("fk_notification_read_notification"), new TableField[] { MbNotificationRead.MB_NOTIFICATION_READ.NOTIFICATION_ID }, Keys.MB_NOTIFICATION_PKEY, new TableField[] { MbNotification.MB_NOTIFICATION.ID }, true);
    public static final ForeignKey<MbNotificationReadRecord, MbIamUserRecord> MB_NOTIFICATION_READ__FK_NOTIFICATION_READ_USER = Internal.createForeignKey(MbNotificationRead.MB_NOTIFICATION_READ, DSL.name("fk_notification_read_user"), new TableField[] { MbNotificationRead.MB_NOTIFICATION_READ.USER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
    public static final ForeignKey<MbOperationLogRecord, MbIamUserRecord> MB_OPERATION_LOG__FK_OPERATION_LOG_USER = Internal.createForeignKey(MbOperationLog.MB_OPERATION_LOG, DSL.name("fk_operation_log_user"), new TableField[] { MbOperationLog.MB_OPERATION_LOG.USER_ID }, Keys.MB_IAM_USER_PKEY, new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
}
