/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema;


import com.metabuild.schema.tables.MbIamUser;
import com.metabuild.schema.tables.records.MbIamUserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MbIamUserRecord> MB_IAM_USER_PKEY = Internal.createUniqueKey(MbIamUser.MB_IAM_USER, DSL.name("mb_iam_user_pkey"), new TableField[] { MbIamUser.MB_IAM_USER.ID }, true);
}
