/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.BizNotice;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知公告
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNoticeRecord extends UpdatableRecordImpl<BizNoticeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.biz_notice.id</code>. 主键（Snowflake）
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.biz_notice.id</code>. 主键（Snowflake）
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.biz_notice.tenant_id</code>. 租户 ID（v1 默认 0）
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.biz_notice.tenant_id</code>. 租户 ID（v1 默认 0）
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.biz_notice.title</code>. 公告标题
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.biz_notice.title</code>. 公告标题
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.biz_notice.content</code>. 公告内容（富文本 HTML，后端 jsoup
     * 净化）
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.biz_notice.content</code>. 公告内容（富文本 HTML，后端 jsoup
     * 净化）
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.biz_notice.status</code>. 状态：0=草稿 1=已发布 2=已撤回
     */
    public void setStatus(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.biz_notice.status</code>. 状态：0=草稿 1=已发布 2=已撤回
     */
    public Short getStatus() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.biz_notice.pinned</code>. 是否置顶
     */
    public void setPinned(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.biz_notice.pinned</code>. 是否置顶
     */
    public Boolean getPinned() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.biz_notice.start_time</code>. 生效开始时间
     */
    public void setStartTime(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.biz_notice.start_time</code>. 生效开始时间
     */
    public OffsetDateTime getStartTime() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.biz_notice.end_time</code>. 生效结束时间
     */
    public void setEndTime(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.biz_notice.end_time</code>. 生效结束时间
     */
    public OffsetDateTime getEndTime() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.biz_notice.owner_dept_id</code>. 所属部门 ID（数据权限）
     */
    public void setOwnerDeptId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.biz_notice.owner_dept_id</code>. 所属部门 ID（数据权限）
     */
    public Long getOwnerDeptId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.biz_notice.version</code>. 乐观锁版本号
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.biz_notice.version</code>. 乐观锁版本号
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.biz_notice.created_by</code>. 创建人 ID
     */
    public void setCreatedBy(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.biz_notice.created_by</code>. 创建人 ID
     */
    public Long getCreatedBy() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.biz_notice.created_at</code>. 创建时间
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.biz_notice.created_at</code>. 创建时间
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.biz_notice.updated_by</code>. 最后修改人 ID
     */
    public void setUpdatedBy(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.biz_notice.updated_by</code>. 最后修改人 ID
     */
    public Long getUpdatedBy() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.biz_notice.updated_at</code>. 最后修改时间
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.biz_notice.updated_at</code>. 最后修改时间
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizNoticeRecord
     */
    public BizNoticeRecord() {
        super(BizNotice.BIZ_NOTICE);
    }

    /**
     * Create a detached, initialised BizNoticeRecord
     */
    public BizNoticeRecord(Long id, Long tenantId, String title, String content, Short status, Boolean pinned, OffsetDateTime startTime, OffsetDateTime endTime, Long ownerDeptId, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(BizNotice.BIZ_NOTICE);

        setId(id);
        setTenantId(tenantId);
        setTitle(title);
        setContent(content);
        setStatus(status);
        setPinned(pinned);
        setStartTime(startTime);
        setEndTime(endTime);
        setOwnerDeptId(ownerDeptId);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
