/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.BizNoticeTarget;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知目标（多态关联：全员/部门/角色/用户）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNoticeTargetRecord extends UpdatableRecordImpl<BizNoticeTargetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.biz_notice_target.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.biz_notice_target.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.biz_notice_target.notice_id</code>.
     */
    public void setNoticeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.biz_notice_target.notice_id</code>.
     */
    public Long getNoticeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.biz_notice_target.target_type</code>. 目标类型：ALL=全员
     * DEPT=部门 ROLE=角色 USER=指定用户
     */
    public void setTargetType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.biz_notice_target.target_type</code>. 目标类型：ALL=全员
     * DEPT=部门 ROLE=角色 USER=指定用户
     */
    public String getTargetType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.biz_notice_target.target_id</code>. 目标 ID（ALL 时为
     * NULL，DEPT=部门ID，ROLE=角色ID，USER=用户ID）
     */
    public void setTargetId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.biz_notice_target.target_id</code>. 目标 ID（ALL 时为
     * NULL，DEPT=部门ID，ROLE=角色ID，USER=用户ID）
     */
    public Long getTargetId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.biz_notice_target.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.biz_notice_target.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizNoticeTargetRecord
     */
    public BizNoticeTargetRecord() {
        super(BizNoticeTarget.BIZ_NOTICE_TARGET);
    }

    /**
     * Create a detached, initialised BizNoticeTargetRecord
     */
    public BizNoticeTargetRecord(Long id, Long noticeId, String targetType, Long targetId, OffsetDateTime createdAt) {
        super(BizNoticeTarget.BIZ_NOTICE_TARGET);

        setId(id);
        setNoticeId(noticeId);
        setTargetType(targetType);
        setTargetId(targetId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
