/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.BizNoticeAttachment;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 公告附件关联
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNoticeAttachmentRecord extends UpdatableRecordImpl<BizNoticeAttachmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.biz_notice_attachment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.biz_notice_attachment.notice_id</code>.
     */
    public void setNoticeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.notice_id</code>.
     */
    public Long getNoticeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.biz_notice_attachment.file_id</code>.
     */
    public void setFileId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.file_id</code>.
     */
    public Long getFileId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.biz_notice_attachment.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.biz_notice_attachment.tenant_id</code>. 租户 ID
     */
    public void setTenantId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.tenant_id</code>. 租户 ID
     */
    public Long getTenantId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.biz_notice_attachment.created_by</code>. 创建人 ID
     */
    public void setCreatedBy(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.created_by</code>. 创建人 ID
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.biz_notice_attachment.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.biz_notice_attachment.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizNoticeAttachmentRecord
     */
    public BizNoticeAttachmentRecord() {
        super(BizNoticeAttachment.BIZ_NOTICE_ATTACHMENT);
    }

    /**
     * Create a detached, initialised BizNoticeAttachmentRecord
     */
    public BizNoticeAttachmentRecord(Long id, Long noticeId, Long fileId, Integer sortOrder, Long tenantId, Long createdBy, OffsetDateTime createdAt) {
        super(BizNoticeAttachment.BIZ_NOTICE_ATTACHMENT);

        setId(id);
        setNoticeId(noticeId);
        setFileId(fileId);
        setSortOrder(sortOrder);
        setTenantId(tenantId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
