/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.BizNoticeRecipient;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知接收人（发布时从 target 展开到具体用户）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BizNoticeRecipientRecord extends UpdatableRecordImpl<BizNoticeRecipientRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.biz_notice_recipient.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.biz_notice_recipient.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.biz_notice_recipient.notice_id</code>.
     */
    public void setNoticeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.biz_notice_recipient.notice_id</code>.
     */
    public Long getNoticeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.biz_notice_recipient.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.biz_notice_recipient.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.biz_notice_recipient.read_at</code>.
     * 已读时间（NULL=未读）
     */
    public void setReadAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.biz_notice_recipient.read_at</code>.
     * 已读时间（NULL=未读）
     */
    public OffsetDateTime getReadAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.biz_notice_recipient.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.biz_notice_recipient.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BizNoticeRecipientRecord
     */
    public BizNoticeRecipientRecord() {
        super(BizNoticeRecipient.BIZ_NOTICE_RECIPIENT);
    }

    /**
     * Create a detached, initialised BizNoticeRecipientRecord
     */
    public BizNoticeRecipientRecord(Long id, Long noticeId, Long userId, OffsetDateTime readAt, OffsetDateTime createdAt) {
        super(BizNoticeRecipient.BIZ_NOTICE_RECIPIENT);

        setId(id);
        setNoticeId(noticeId);
        setUserId(userId);
        setReadAt(readAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
