/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbConfig;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统配置表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbConfigRecord extends UpdatableRecordImpl<MbConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_config.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_config.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_config.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_config.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_config.config_key</code>.
     */
    public void setConfigKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_config.config_key</code>.
     */
    public String getConfigKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_config.config_value</code>.
     */
    public void setConfigValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_config.config_value</code>.
     */
    public String getConfigValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_config.config_type</code>.
     */
    public void setConfigType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_config.config_type</code>.
     */
    public String getConfigType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_config.remark</code>.
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_config.remark</code>.
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_config.version</code>.
     */
    public void setVersion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_config.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.mb_config.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_config.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.mb_config.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_config.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.mb_config.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_config.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.mb_config.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_config.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbConfigRecord
     */
    public MbConfigRecord() {
        super(MbConfig.MB_CONFIG);
    }

    /**
     * Create a detached, initialised MbConfigRecord
     */
    public MbConfigRecord(Long id, Long tenantId, String configKey, String configValue, String configType, String remark, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbConfig.MB_CONFIG);

        setId(id);
        setTenantId(tenantId);
        setConfigKey(configKey);
        setConfigValue(configValue);
        setConfigType(configType);
        setRemark(remark);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
