/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbDictType;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 字典类型表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictTypeRecord extends UpdatableRecordImpl<MbDictTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_dict_type.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_dict_type.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_dict_type.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_dict_type.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_dict_type.status</code>.
     */
    public void setStatus(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.status</code>.
     */
    public Short getStatus() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.mb_dict_type.remark</code>.
     */
    public void setRemark(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.remark</code>.
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_dict_type.owner_dept_id</code>.
     */
    public void setOwnerDeptId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.owner_dept_id</code>.
     */
    public Long getOwnerDeptId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.mb_dict_type.version</code>.
     */
    public void setVersion(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.mb_dict_type.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.mb_dict_type.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.mb_dict_type.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.mb_dict_type.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_dict_type.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbDictTypeRecord
     */
    public MbDictTypeRecord() {
        super(MbDictType.MB_DICT_TYPE);
    }

    /**
     * Create a detached, initialised MbDictTypeRecord
     */
    public MbDictTypeRecord(Long id, Long tenantId, String name, String code, Short status, String remark, Long ownerDeptId, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbDictType.MB_DICT_TYPE);

        setId(id);
        setTenantId(tenantId);
        setName(name);
        setCode(code);
        setStatus(status);
        setRemark(remark);
        setOwnerDeptId(ownerDeptId);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
