/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbDictData;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 字典数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbDictDataRecord extends UpdatableRecordImpl<MbDictDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_dict_data.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_dict_data.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_dict_data.dict_type_id</code>.
     */
    public void setDictTypeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.dict_type_id</code>.
     */
    public Long getDictTypeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_dict_data.label</code>.
     */
    public void setLabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_dict_data.value</code>.
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.value</code>.
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_dict_data.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.mb_dict_data.status</code>.
     */
    public void setStatus(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.status</code>.
     */
    public Short getStatus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.mb_dict_data.css_class</code>.
     */
    public void setCssClass(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.css_class</code>.
     */
    public String getCssClass() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_dict_data.remark</code>.
     */
    public void setRemark(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.remark</code>.
     */
    public String getRemark() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_dict_data.version</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.mb_dict_data.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.mb_dict_data.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.mb_dict_data.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.mb_dict_data.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_dict_data.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbDictDataRecord
     */
    public MbDictDataRecord() {
        super(MbDictData.MB_DICT_DATA);
    }

    /**
     * Create a detached, initialised MbDictDataRecord
     */
    public MbDictDataRecord(Long id, Long tenantId, Long dictTypeId, String label, String value, Integer sortOrder, Short status, String cssClass, String remark, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbDictData.MB_DICT_DATA);

        setId(id);
        setTenantId(tenantId);
        setDictTypeId(dictTypeId);
        setLabel(label);
        setValue(value);
        setSortOrder(sortOrder);
        setStatus(status);
        setCssClass(cssClass);
        setRemark(remark);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
