/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamRoleMenu;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色-菜单关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRoleMenuRecord extends UpdatableRecordImpl<MbIamRoleMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_role_menu.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_role_menu.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_role_menu.menu_id</code>.
     */
    public void setMenuId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_role_menu.menu_id</code>.
     */
    public Long getMenuId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamRoleMenuRecord
     */
    public MbIamRoleMenuRecord() {
        super(MbIamRoleMenu.MB_IAM_ROLE_MENU);
    }

    /**
     * Create a detached, initialised MbIamRoleMenuRecord
     */
    public MbIamRoleMenuRecord(Long roleId, Long menuId) {
        super(MbIamRoleMenu.MB_IAM_ROLE_MENU);

        setRoleId(roleId);
        setMenuId(menuId);
        resetChangedOnNotNull();
    }
}
