/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamRouteTree;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 路由树
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRouteTreeRecord extends UpdatableRecordImpl<MbIamRouteTreeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_route_tree.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.path</code>.
     */
    public void setPath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.path</code>.
     */
    public String getPath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.component</code>.
     */
    public void setComponent(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.component</code>.
     */
    public String getComponent() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.redirect</code>.
     */
    public void setRedirect(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.redirect</code>.
     */
    public String getRedirect() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.icon</code>.
     */
    public void setIcon(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.icon</code>.
     */
    public String getIcon() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.hidden</code>.
     */
    public void setHidden(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.hidden</code>.
     */
    public Boolean getHidden() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.permission_code</code>.
     */
    public void setPermissionCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.permission_code</code>.
     */
    public String getPermissionCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.route_type</code>.
     */
    public void setRouteType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.route_type</code>.
     */
    public String getRouteType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.version</code>.
     */
    public void setVersion(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.mb_iam_route_tree.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.mb_iam_route_tree.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamRouteTreeRecord
     */
    public MbIamRouteTreeRecord() {
        super(MbIamRouteTree.MB_IAM_ROUTE_TREE);
    }

    /**
     * Create a detached, initialised MbIamRouteTreeRecord
     */
    public MbIamRouteTreeRecord(Long id, Long tenantId, Long parentId, String path, String name, String component, String redirect, String icon, Integer sortOrder, Boolean hidden, String permissionCode, String routeType, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbIamRouteTree.MB_IAM_ROUTE_TREE);

        setId(id);
        setTenantId(tenantId);
        setParentId(parentId);
        setPath(path);
        setName(name);
        setComponent(component);
        setRedirect(redirect);
        setIcon(icon);
        setSortOrder(sortOrder);
        setHidden(hidden);
        setPermissionCode(permissionCode);
        setRouteType(routeType);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
