/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamRoleDataScopeDept;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色-数据权限自定义部门关联表（CUSTOM_DEPT 时使用）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRoleDataScopeDeptRecord extends UpdatableRecordImpl<MbIamRoleDataScopeDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_role_data_scope_dept.role_id</code>.
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_role_data_scope_dept.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_role_data_scope_dept.dept_id</code>.
     */
    public void setDeptId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_role_data_scope_dept.dept_id</code>.
     */
    public Long getDeptId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamRoleDataScopeDeptRecord
     */
    public MbIamRoleDataScopeDeptRecord() {
        super(MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT);
    }

    /**
     * Create a detached, initialised MbIamRoleDataScopeDeptRecord
     */
    public MbIamRoleDataScopeDeptRecord(Long roleId, Long deptId) {
        super(MbIamRoleDataScopeDept.MB_IAM_ROLE_DATA_SCOPE_DEPT);

        setRoleId(roleId);
        setDeptId(deptId);
        resetChangedOnNotNull();
    }
}
