/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamDept;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 部门表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamDeptRecord extends UpdatableRecordImpl<MbIamDeptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_dept.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_dept.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_iam_dept.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_iam_dept.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_iam_dept.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.mb_iam_dept.status</code>.
     */
    public void setStatus(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.status</code>.
     */
    public Short getStatus() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.mb_iam_dept.leader_user_id</code>.
     */
    public void setLeaderUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.leader_user_id</code>.
     */
    public Long getLeaderUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.mb_iam_dept.owner_dept_id</code>.
     */
    public void setOwnerDeptId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.owner_dept_id</code>.
     */
    public Long getOwnerDeptId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.mb_iam_dept.version</code>.
     */
    public void setVersion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.mb_iam_dept.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.mb_iam_dept.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.mb_iam_dept.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.mb_iam_dept.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_iam_dept.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamDeptRecord
     */
    public MbIamDeptRecord() {
        super(MbIamDept.MB_IAM_DEPT);
    }

    /**
     * Create a detached, initialised MbIamDeptRecord
     */
    public MbIamDeptRecord(Long id, Long tenantId, Long parentId, String name, Integer sortOrder, Short status, Long leaderUserId, Long ownerDeptId, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbIamDept.MB_IAM_DEPT);

        setId(id);
        setTenantId(tenantId);
        setParentId(parentId);
        setName(name);
        setSortOrder(sortOrder);
        setStatus(status);
        setLeaderUserId(leaderUserId);
        setOwnerDeptId(ownerDeptId);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
