/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamMenu;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 菜单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamMenuRecord extends UpdatableRecordImpl<MbIamMenuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_menu.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_menu.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_iam_menu.parent_id</code>.
     */
    public void setParentId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.parent_id</code>.
     */
    public Long getParentId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_iam_menu.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_iam_menu.permission_code</code>.
     */
    public void setPermissionCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.permission_code</code>.
     */
    public String getPermissionCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_iam_menu.menu_type</code>.
     */
    public void setMenuType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.menu_type</code>.
     */
    public String getMenuType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_iam_menu.icon</code>.
     */
    public void setIcon(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.icon</code>.
     */
    public String getIcon() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_iam_menu.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.mb_iam_menu.visible</code>.
     */
    public void setVisible(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.mb_iam_menu.version</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.mb_iam_menu.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.mb_iam_menu.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.mb_iam_menu.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.mb_iam_menu.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_iam_menu.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamMenuRecord
     */
    public MbIamMenuRecord() {
        super(MbIamMenu.MB_IAM_MENU);
    }

    /**
     * Create a detached, initialised MbIamMenuRecord
     */
    public MbIamMenuRecord(Long id, Long tenantId, Long parentId, String name, String permissionCode, String menuType, String icon, Integer sortOrder, Boolean visible, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbIamMenu.MB_IAM_MENU);

        setId(id);
        setTenantId(tenantId);
        setParentId(parentId);
        setName(name);
        setPermissionCode(permissionCode);
        setMenuType(menuType);
        setIcon(icon);
        setSortOrder(sortOrder);
        setVisible(visible);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
