/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamRole;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamRoleRecord extends UpdatableRecordImpl<MbIamRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_role.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_role.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_iam_role.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_iam_role.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_iam_role.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.mb_iam_role.status</code>.
     */
    public void setStatus(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.status</code>.
     */
    public Short getStatus() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.mb_iam_role.data_scope</code>.
     * 数据权限范围：ALL/CUSTOM_DEPT/OWN_DEPT/OWN_DEPT_AND_CHILD/SELF
     */
    public void setDataScope(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.data_scope</code>.
     * 数据权限范围：ALL/CUSTOM_DEPT/OWN_DEPT/OWN_DEPT_AND_CHILD/SELF
     */
    public String getDataScope() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_iam_role.remark</code>.
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.remark</code>.
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_iam_role.owner_dept_id</code>.
     */
    public void setOwnerDeptId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.owner_dept_id</code>.
     */
    public Long getOwnerDeptId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.mb_iam_role.version</code>.
     */
    public void setVersion(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.mb_iam_role.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.mb_iam_role.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.mb_iam_role.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.mb_iam_role.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_iam_role.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamRoleRecord
     */
    public MbIamRoleRecord() {
        super(MbIamRole.MB_IAM_ROLE);
    }

    /**
     * Create a detached, initialised MbIamRoleRecord
     */
    public MbIamRoleRecord(Long id, Long tenantId, String name, String code, Integer sortOrder, Short status, String dataScope, String remark, Long ownerDeptId, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbIamRole.MB_IAM_ROLE);

        setId(id);
        setTenantId(tenantId);
        setName(name);
        setCode(code);
        setSortOrder(sortOrder);
        setStatus(status);
        setDataScope(dataScope);
        setRemark(remark);
        setOwnerDeptId(ownerDeptId);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
