/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamUser;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamUserRecord extends UpdatableRecordImpl<MbIamUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_user.id</code>. 用户 ID（Snowflake）
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.id</code>. 用户 ID（Snowflake）
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_user.tenant_id</code>. 租户 ID（v1 固定为
     * 0，v1.5+ 启用多租户）
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.tenant_id</code>. 租户 ID（v1 固定为
     * 0，v1.5+ 启用多租户）
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_iam_user.username</code>.
     */
    public void setUsername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.username</code>.
     */
    public String getUsername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_iam_user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_iam_user.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_iam_user.phone</code>.
     */
    public void setPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.phone</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_iam_user.nickname</code>.
     */
    public void setNickname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.nickname</code>.
     */
    public String getNickname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_iam_user.avatar</code>.
     */
    public void setAvatar(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_iam_user.dept_id</code>.
     */
    public void setDeptId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.dept_id</code>.
     */
    public Long getDeptId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.mb_iam_user.status</code>. 状态：1=启用，0=停用
     */
    public void setStatus(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.status</code>. 状态：1=启用，0=停用
     */
    public Short getStatus() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.mb_iam_user.owner_dept_id</code>. 数据权限归属部门
     */
    public void setOwnerDeptId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.owner_dept_id</code>. 数据权限归属部门
     */
    public Long getOwnerDeptId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.mb_iam_user.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.mb_iam_user.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.mb_iam_user.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.mb_iam_user.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.mb_iam_user.version</code>.
     */
    public void setVersion(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.mb_iam_user.password_updated_at</code>.
     */
    public void setPasswordUpdatedAt(OffsetDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.password_updated_at</code>.
     */
    public OffsetDateTime getPasswordUpdatedAt() {
        return (OffsetDateTime) get(16);
    }

    /**
     * Setter for <code>public.mb_iam_user.must_change_password</code>.
     */
    public void setMustChangePassword(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.mb_iam_user.must_change_password</code>.
     */
    public Boolean getMustChangePassword() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamUserRecord
     */
    public MbIamUserRecord() {
        super(MbIamUser.MB_IAM_USER);
    }

    /**
     * Create a detached, initialised MbIamUserRecord
     */
    public MbIamUserRecord(Long id, Long tenantId, String username, String passwordHash, String email, String phone, String nickname, String avatar, Long deptId, Short status, Long ownerDeptId, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt, Integer version, OffsetDateTime passwordUpdatedAt, Boolean mustChangePassword) {
        super(MbIamUser.MB_IAM_USER);

        setId(id);
        setTenantId(tenantId);
        setUsername(username);
        setPasswordHash(passwordHash);
        setEmail(email);
        setPhone(phone);
        setNickname(nickname);
        setAvatar(avatar);
        setDeptId(deptId);
        setStatus(status);
        setOwnerDeptId(ownerDeptId);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        setVersion(version);
        setPasswordUpdatedAt(passwordUpdatedAt);
        setMustChangePassword(mustChangePassword);
        resetChangedOnNotNull();
    }
}
