/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbIamPasswordHistory;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 密码历史表（防重用）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbIamPasswordHistoryRecord extends UpdatableRecordImpl<MbIamPasswordHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_iam_password_history.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_iam_password_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_iam_password_history.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_iam_password_history.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_iam_password_history.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_iam_password_history.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_iam_password_history.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_iam_password_history.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbIamPasswordHistoryRecord
     */
    public MbIamPasswordHistoryRecord() {
        super(MbIamPasswordHistory.MB_IAM_PASSWORD_HISTORY);
    }

    /**
     * Create a detached, initialised MbIamPasswordHistoryRecord
     */
    public MbIamPasswordHistoryRecord(Long id, Long userId, String passwordHash, OffsetDateTime createdAt) {
        super(MbIamPasswordHistory.MB_IAM_PASSWORD_HISTORY);

        setId(id);
        setUserId(userId);
        setPasswordHash(passwordHash);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
