/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbJobLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 定时任务日志（追加表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbJobLogRecord extends UpdatableRecordImpl<MbJobLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_job_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_job_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_job_log.job_name</code>.
     */
    public void setJobName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_job_log.job_name</code>.
     */
    public String getJobName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.mb_job_log.status</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_job_log.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_job_log.start_time</code>.
     */
    public void setStartTime(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_job_log.start_time</code>.
     */
    public OffsetDateTime getStartTime() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.mb_job_log.end_time</code>.
     */
    public void setEndTime(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_job_log.end_time</code>.
     */
    public OffsetDateTime getEndTime() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.mb_job_log.duration_ms</code>.
     */
    public void setDurationMs(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_job_log.duration_ms</code>.
     */
    public Long getDurationMs() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.mb_job_log.error_message</code>.
     */
    public void setErrorMessage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_job_log.error_message</code>.
     */
    public String getErrorMessage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_job_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_job_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbJobLogRecord
     */
    public MbJobLogRecord() {
        super(MbJobLog.MB_JOB_LOG);
    }

    /**
     * Create a detached, initialised MbJobLogRecord
     */
    public MbJobLogRecord(Long id, String jobName, String status, OffsetDateTime startTime, OffsetDateTime endTime, Long durationMs, String errorMessage, OffsetDateTime createdAt) {
        super(MbJobLog.MB_JOB_LOG);

        setId(id);
        setJobName(jobName);
        setStatus(status);
        setStartTime(startTime);
        setEndTime(endTime);
        setDurationMs(durationMs);
        setErrorMessage(errorMessage);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
