/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbNotificationDeliveryLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知投递日志（按渠道维度，区别于按收件人维度的 mb_notification_log）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationDeliveryLogRecord extends UpdatableRecordImpl<MbNotificationDeliveryLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_notification_delivery_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.notice_id</code>.
     * 业务来源 ID（如 notice.id），可空
     */
    public void setNoticeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.notice_id</code>.
     * 业务来源 ID（如 notice.id），可空
     */
    public Long getNoticeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.message_type</code>.
     * 消息类型，如 NOTICE_PUBLISHED
     */
    public void setMessageType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.message_type</code>.
     * 消息类型，如 NOTICE_PUBLISHED
     */
    public String getMessageType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.channel</code>.
     * 渠道：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public void setChannel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.channel</code>.
     * 渠道：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public String getChannel() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.mb_notification_delivery_log.recipient_count</code>.
     * 本次投递的收件人数量
     */
    public void setRecipientCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.mb_notification_delivery_log.recipient_count</code>.
     * 本次投递的收件人数量
     */
    public Integer getRecipientCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.status</code>.
     * 状态：SUCCESS/TIMEOUT/FAILED
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.status</code>.
     * 状态：SUCCESS/TIMEOUT/FAILED
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.duration_ms</code>.
     * 耗时（毫秒）
     */
    public void setDurationMs(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.duration_ms</code>.
     * 耗时（毫秒）
     */
    public Integer getDurationMs() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.error_code</code>.
     * 失败错误码
     */
    public void setErrorCode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.error_code</code>.
     * 失败错误码
     */
    public String getErrorCode() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.mb_notification_delivery_log.error_message</code>. 失败信息（最多
     * 500 字符）
     */
    public void setErrorMessage(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.mb_notification_delivery_log.error_message</code>. 失败信息（最多
     * 500 字符）
     */
    public String getErrorMessage() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbNotificationDeliveryLogRecord
     */
    public MbNotificationDeliveryLogRecord() {
        super(MbNotificationDeliveryLog.MB_NOTIFICATION_DELIVERY_LOG);
    }

    /**
     * Create a detached, initialised MbNotificationDeliveryLogRecord
     */
    public MbNotificationDeliveryLogRecord(Long id, Long tenantId, Long noticeId, String messageType, String channel, Integer recipientCount, String status, Integer durationMs, String errorCode, String errorMessage, OffsetDateTime createdAt) {
        super(MbNotificationDeliveryLog.MB_NOTIFICATION_DELIVERY_LOG);

        setId(id);
        setTenantId(tenantId);
        setNoticeId(noticeId);
        setMessageType(messageType);
        setChannel(channel);
        setRecipientCount(recipientCount);
        setStatus(status);
        setDurationMs(durationMs);
        setErrorCode(errorCode);
        setErrorMessage(errorMessage);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
