/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbNotificationLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知发送记录
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationLogRecord extends UpdatableRecordImpl<MbNotificationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_notification_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_notification_log.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_notification_log.channel_type</code>.
     * 渠道类型：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public void setChannelType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.channel_type</code>.
     * 渠道类型：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public String getChannelType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_notification_log.recipient_id</code>. 接收人用户 ID
     */
    public void setRecipientId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.recipient_id</code>. 接收人用户 ID
     */
    public Long getRecipientId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.mb_notification_log.template_code</code>. 模板编码
     */
    public void setTemplateCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.template_code</code>. 模板编码
     */
    public String getTemplateCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_notification_log.module</code>.
     * 来源模块（notice/order/...）
     */
    public void setModule(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.module</code>.
     * 来源模块（notice/order/...）
     */
    public String getModule() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_notification_log.reference_id</code>. 关联业务 ID
     */
    public void setReferenceId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.reference_id</code>. 关联业务 ID
     */
    public String getReferenceId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_notification_log.status</code>. 状态：0=pending
     * 1=success 2=failed
     */
    public void setStatus(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.status</code>. 状态：0=pending
     * 1=success 2=failed
     */
    public Short getStatus() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.mb_notification_log.error_message</code>. 失败原因
     */
    public void setErrorMessage(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.error_message</code>. 失败原因
     */
    public String getErrorMessage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_notification_log.sent_at</code>. 发送时间
     */
    public void setSentAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.sent_at</code>. 发送时间
     */
    public OffsetDateTime getSentAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.mb_notification_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_notification_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbNotificationLogRecord
     */
    public MbNotificationLogRecord() {
        super(MbNotificationLog.MB_NOTIFICATION_LOG);
    }

    /**
     * Create a detached, initialised MbNotificationLogRecord
     */
    public MbNotificationLogRecord(Long id, Long tenantId, String channelType, Long recipientId, String templateCode, String module, String referenceId, Short status, String errorMessage, OffsetDateTime sentAt, OffsetDateTime createdAt) {
        super(MbNotificationLog.MB_NOTIFICATION_LOG);

        setId(id);
        setTenantId(tenantId);
        setChannelType(channelType);
        setRecipientId(recipientId);
        setTemplateCode(templateCode);
        setModule(module);
        setReferenceId(referenceId);
        setStatus(status);
        setErrorMessage(errorMessage);
        setSentAt(sentAt);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
