/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbNotificationDeliveryLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知投递日志（按渠道维度，区别于按收件人维度的 mb_notification_log）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationDeliveryLogRecord extends UpdatableRecordImpl<MbNotificationDeliveryLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_notification_delivery_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.business_id</code>.
     * 业务来源 ID（notice.id / order.id / approval.id），由 business_type 区分
     */
    public void setBusinessId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.business_id</code>.
     * 业务来源 ID（notice.id / order.id / approval.id），由 business_type 区分
     */
    public Long getBusinessId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.channel</code>.
     * 渠道：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public void setChannel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.channel</code>.
     * 渠道：IN_APP/EMAIL/WECHAT_MP/WECHAT_MINI
     */
    public String getChannel() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.mb_notification_delivery_log.recipient_count</code>.
     * 本次投递的收件人数量
     */
    public void setRecipientCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.mb_notification_delivery_log.recipient_count</code>.
     * 本次投递的收件人数量
     */
    public Integer getRecipientCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.status</code>.
     * 状态：SUCCESS/TIMEOUT/FAILED
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.status</code>.
     * 状态：SUCCESS/TIMEOUT/FAILED
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.duration_ms</code>.
     * 耗时（毫秒，BIGINT）
     */
    public void setDurationMs(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.duration_ms</code>.
     * 耗时（毫秒，BIGINT）
     */
    public Long getDurationMs() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.error_code</code>.
     * 失败错误码
     */
    public void setErrorCode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.error_code</code>.
     * 失败错误码
     */
    public String getErrorCode() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>public.mb_notification_delivery_log.error_message</code>. 失败信息（最多
     * 500 字符）
     */
    public void setErrorMessage(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.mb_notification_delivery_log.error_message</code>. 失败信息（最多
     * 500 字符）
     */
    public String getErrorMessage() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for
     * <code>public.mb_notification_delivery_log.business_type</code>.
     * 业务大类：NOTICE / ORDER / APPROVAL 等
     */
    public void setBusinessType(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.mb_notification_delivery_log.business_type</code>.
     * 业务大类：NOTICE / ORDER / APPROVAL 等
     */
    public String getBusinessType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.event_type</code>.
     * 业务事件：NOTICE_PUBLISHED / ORDER_SHIPPED 等
     */
    public void setEventType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.event_type</code>.
     * 业务事件：NOTICE_PUBLISHED / ORDER_SHIPPED 等
     */
    public String getEventType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.message_type</code>.
     * 消息格式：TEXT / HTML / TEMPLATE / CARD 等（区别于 channel 投递渠道）
     */
    public void setMessageType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.message_type</code>.
     * 消息格式：TEXT / HTML / TEMPLATE / CARD 等（区别于 channel 投递渠道）
     */
    public String getMessageType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.mb_notification_delivery_log.trace_id</code>. MDC
     * 链路追踪 ID，关联 ELK / OpenTelemetry 日志
     */
    public void setTraceId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_notification_delivery_log.trace_id</code>. MDC
     * 链路追踪 ID，关联 ELK / OpenTelemetry 日志
     */
    public String getTraceId() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbNotificationDeliveryLogRecord
     */
    public MbNotificationDeliveryLogRecord() {
        super(MbNotificationDeliveryLog.MB_NOTIFICATION_DELIVERY_LOG);
    }

    /**
     * Create a detached, initialised MbNotificationDeliveryLogRecord
     */
    public MbNotificationDeliveryLogRecord(Long id, Long tenantId, Long businessId, String channel, Integer recipientCount, String status, Long durationMs, String errorCode, String errorMessage, OffsetDateTime createdAt, String businessType, String eventType, String messageType, String traceId) {
        super(MbNotificationDeliveryLog.MB_NOTIFICATION_DELIVERY_LOG);

        setId(id);
        setTenantId(tenantId);
        setBusinessId(businessId);
        setChannel(channel);
        setRecipientCount(recipientCount);
        setStatus(status);
        setDurationMs(durationMs);
        setErrorCode(errorCode);
        setErrorMessage(errorMessage);
        setCreatedAt(createdAt);
        setBusinessType(businessType);
        setEventType(eventType);
        setMessageType(messageType);
        setTraceId(traceId);
        resetChangedOnNotNull();
    }
}
