/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbNotificationRead;

import java.time.OffsetDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知已读记录（追加表）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationReadRecord extends UpdatableRecordImpl<MbNotificationReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_notification_read.notification_id</code>.
     */
    public void setNotificationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_notification_read.notification_id</code>.
     */
    public Long getNotificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_notification_read.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_notification_read.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_notification_read.read_at</code>.
     */
    public void setReadAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_notification_read.read_at</code>.
     */
    public OffsetDateTime getReadAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbNotificationReadRecord
     */
    public MbNotificationReadRecord() {
        super(MbNotificationRead.MB_NOTIFICATION_READ);
    }

    /**
     * Create a detached, initialised MbNotificationReadRecord
     */
    public MbNotificationReadRecord(Long notificationId, Long userId, OffsetDateTime readAt) {
        super(MbNotificationRead.MB_NOTIFICATION_READ);

        setNotificationId(notificationId);
        setUserId(userId);
        setReadAt(readAt);
        resetChangedOnNotNull();
    }
}
