/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbNotification;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 通知公告表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbNotificationRecord extends UpdatableRecordImpl<MbNotificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_notification.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_notification.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_notification.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_notification.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_notification.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_notification.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.mb_notification.content</code>.
     */
    public void setContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_notification.content</code>.
     */
    public String getContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_notification.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_notification.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_notification.sender_id</code>.
     */
    public void setSenderId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_notification.sender_id</code>.
     */
    public Long getSenderId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.mb_notification.status</code>.
     */
    public void setStatus(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_notification.status</code>.
     */
    public Short getStatus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.mb_notification.owner_dept_id</code>.
     */
    public void setOwnerDeptId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_notification.owner_dept_id</code>.
     */
    public Long getOwnerDeptId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.mb_notification.version</code>.
     */
    public void setVersion(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_notification.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.mb_notification.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_notification.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.mb_notification.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_notification.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.mb_notification.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_notification.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.mb_notification.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_notification.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbNotificationRecord
     */
    public MbNotificationRecord() {
        super(MbNotification.MB_NOTIFICATION);
    }

    /**
     * Create a detached, initialised MbNotificationRecord
     */
    public MbNotificationRecord(Long id, Long tenantId, String title, String content, String type, Long senderId, Short status, Long ownerDeptId, Integer version, Long createdBy, OffsetDateTime createdAt, Long updatedBy, OffsetDateTime updatedAt) {
        super(MbNotification.MB_NOTIFICATION);

        setId(id);
        setTenantId(tenantId);
        setTitle(title);
        setContent(content);
        setType(type);
        setSenderId(senderId);
        setStatus(status);
        setOwnerDeptId(ownerDeptId);
        setVersion(version);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
