/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbOperationLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 操作日志（追加表，不注册 DataScope）
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbOperationLogRecord extends UpdatableRecordImpl<MbOperationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_operation_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_operation_log.tenant_id</code>.
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.tenant_id</code>.
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_operation_log.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_operation_log.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_operation_log.module</code>.
     */
    public void setModule(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.module</code>.
     */
    public String getModule() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_operation_log.operation</code>.
     */
    public void setOperation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.operation</code>.
     */
    public String getOperation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_operation_log.method</code>.
     */
    public void setMethod(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.method</code>.
     */
    public String getMethod() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_operation_log.request_url</code>.
     */
    public void setRequestUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.request_url</code>.
     */
    public String getRequestUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_operation_log.request_params</code>.
     */
    public void setRequestParams(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.request_params</code>.
     */
    public String getRequestParams() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_operation_log.response_result</code>.
     */
    public void setResponseResult(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.response_result</code>.
     */
    public String getResponseResult() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mb_operation_log.ip</code>.
     */
    public void setIp(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.ip</code>.
     */
    public String getIp() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mb_operation_log.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mb_operation_log.duration_ms</code>.
     */
    public void setDurationMs(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.duration_ms</code>.
     */
    public Long getDurationMs() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.mb_operation_log.success</code>.
     */
    public void setSuccess(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.success</code>.
     */
    public Boolean getSuccess() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>public.mb_operation_log.error_message</code>.
     */
    public void setErrorMessage(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.error_message</code>.
     */
    public String getErrorMessage() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.mb_operation_log.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.mb_operation_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbOperationLogRecord
     */
    public MbOperationLogRecord() {
        super(MbOperationLog.MB_OPERATION_LOG);
    }

    /**
     * Create a detached, initialised MbOperationLogRecord
     */
    public MbOperationLogRecord(Long id, Long tenantId, Long userId, String username, String module, String operation, String method, String requestUrl, String requestParams, String responseResult, String ip, String userAgent, Long durationMs, Boolean success, String errorMessage, OffsetDateTime createdAt) {
        super(MbOperationLog.MB_OPERATION_LOG);

        setId(id);
        setTenantId(tenantId);
        setUserId(userId);
        setUsername(username);
        setModule(module);
        setOperation(operation);
        setMethod(method);
        setRequestUrl(requestUrl);
        setRequestParams(requestParams);
        setResponseResult(responseResult);
        setIp(ip);
        setUserAgent(userAgent);
        setDurationMs(durationMs);
        setSuccess(success);
        setErrorMessage(errorMessage);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
