/*
 * This file is generated by jOOQ.
 */
package com.metabuild.schema.tables.records;


import com.metabuild.schema.tables.MbUserWechatBinding;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 微信绑定关系
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MbUserWechatBindingRecord extends UpdatableRecordImpl<MbUserWechatBindingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.mb_user_wechat_binding.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.tenant_id</code>. 租户 ID（v1
     * 默认 0）
     */
    public void setTenantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.tenant_id</code>. 租户 ID（v1
     * 默认 0）
     */
    public Long getTenantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.user_id</code>. 系统用户 ID
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.user_id</code>. 系统用户 ID
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.platform</code>.
     * 平台类型：MP=公众号 MINI=小程序
     */
    public void setPlatform(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.platform</code>.
     * 平台类型：MP=公众号 MINI=小程序
     */
    public String getPlatform() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.app_id</code>. 微信应用 AppID
     */
    public void setAppId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.app_id</code>. 微信应用 AppID
     */
    public String getAppId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.open_id</code>. 微信
     * OpenID（同一用户在不同应用有不同 OpenID）
     */
    public void setOpenId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.open_id</code>. 微信
     * OpenID（同一用户在不同应用有不同 OpenID）
     */
    public String getOpenId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.union_id</code>.
     * UnionID（同一开放平台下多应用共享）
     */
    public void setUnionId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.union_id</code>.
     * UnionID（同一开放平台下多应用共享）
     */
    public String getUnionId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.nickname</code>. 微信昵称
     */
    public void setNickname(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.nickname</code>. 微信昵称
     */
    public String getNickname() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.avatar_url</code>. 微信头像
     * URL
     */
    public void setAvatarUrl(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.avatar_url</code>. 微信头像
     * URL
     */
    public String getAvatarUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mb_user_wechat_binding.bound_at</code>. 绑定时间
     */
    public void setBoundAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mb_user_wechat_binding.bound_at</code>. 绑定时间
     */
    public OffsetDateTime getBoundAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MbUserWechatBindingRecord
     */
    public MbUserWechatBindingRecord() {
        super(MbUserWechatBinding.MB_USER_WECHAT_BINDING);
    }

    /**
     * Create a detached, initialised MbUserWechatBindingRecord
     */
    public MbUserWechatBindingRecord(Long id, Long tenantId, Long userId, String platform, String appId, String openId, String unionId, String nickname, String avatarUrl, OffsetDateTime boundAt) {
        super(MbUserWechatBinding.MB_USER_WECHAT_BINDING);

        setId(id);
        setTenantId(tenantId);
        setUserId(userId);
        setPlatform(platform);
        setAppId(appId);
        setOpenId(openId);
        setUnionId(unionId);
        setNickname(nickname);
        setAvatarUrl(avatarUrl);
        setBoundAt(boundAt);
        resetChangedOnNotNull();
    }
}
